#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

export LOG_PREFIX="vmm"
TMPDIR="$(mktemp --tmpdir -d deploy-tweaks-XXXXXXXX)"
# shellcheck disable=SC2064
trap "rm -rf '${TMPDIR}'" EXIT QUIT TERM HUP INT
ERR_FILE="${TMPDIR}/error"

if [[ -f "./config" ]]; then
    eval "$(grep -E 'DATASTORE_LOCATION|SCRIPTS_REMOTE_DIR' ./config || true)"
elif [[ -f "/var/lib/one/config" ]]; then
    eval "$(grep -E 'DATASTORE_LOCATION|SCRIPTS_REMOTE_DIR' /var/lib/one/config || true)"
fi

set -a -o pipefail

SCRIPT_PATH="$(dirname "$0")"
if [[ -f "${SCRIPT_PATH}/../../etc/vmm/kvm/kvmrc" ]]; then
    # shellcheck source=/dev/null
    source "${SCRIPT_PATH}/../../etc/vmm/kvm/kvmrc"
elif [[ -f "${SCRIPT_PATH}/kvmrc" ]]; then
    # shellcheck source=/dev/null
    source "${SCRIPT_PATH}/kvmrc"
fi
# shellcheck source=/dev/null
source "${SCRIPT_PATH}/../../scripts_common.sh"

if [[ -f "${SCRIPT_PATH}/../../addon-storpoolrc" ]]; then
    # shellcheck source=addon-storpoolrc
    source "${SCRIPT_PATH}/../../addon-storpoolrc"
fi

for var in ONE_PX NVRAM_TEMPLATE_PATH TMPDIR ERR_FILE; do
    [[ -z "${!var}" ]] || export "${var?}"
done

function oneCallXml()
{
    local _CALL="$1" _METHOD="$2" _ID="$3" _OUT_FILE="$4"
    local _ERR_FILE="${TMPDIR}/${_CALL}-${_ID}.error"
    local _TIMEFILE="${TMPDIR}/${_CALL}-${_ID}.time"
    local _RET=1 _ONETRY=${ONE_CALL_RETRIES:-3} _TIME="" _XML_LINES=0
    case "${_CALL}" in
        onevm|onehost|onedatastore)
            read -r -a _ONECMD <<< "${_CALL} ${_METHOD} ${ONE_ARGS:-} -x ${_ID}"
            ;;
        *)
            echo "oneCallXml($*) Error: Unknown call'"
            return 1
            ;;
    esac
    while :; do
        time ("${_ONECMD[@]}" >"${_OUT_FILE}" 2>"${_ERR_FILE}") 2>"${_TIMEFILE}"
        _RET=$?
        _TIME="$(tr '\n' ' ' <"${_TIMEFILE}" | tr '\t' ' ' ||true)"
        _XML_LINES=$(wc -l "${_OUT_FILE}")
        splog "${_ONECMD[*]} # ret=${_RET} time:${_TIME} xmlLines:${_XML_LINES}"
        if [[ ${_RET} -eq 0 ]]; then
            break
        fi
        if [[ ${_ONETRY} -lt 1 ]]; then
            splog "'${_ONECMD[*]} ${_ID}' retry:${_ONETRY} Error: Timeout"
            exit "${_RET}"
        fi
        _ONETRY=$((_ONETRY-1))
        sleep 0.5
    done
    return "${_RET}"
}

if [[ -d /opt/storpool/python3/bin ]]; then
    export PATH="/opt/storpool/python3/bin:${PATH}"
    if [[ -n "${DEBUG_DEPLOY_TWEAKS}" ]]; then
        splog "[D] appending /opt/storpool/python3/bin to PATH=${PATH}"
    fi
fi

function splog()
{
    logger -t "${LOG_PREFIX:-vmm}_sp_${0##*/}" "[$$] $*${DEBUG_LINENO:+ //[${BASH_LINENO[-2]}]}"
}

DEP_FILE="$1"
HOST="$2"
VM_ID="$3"
DEP_NAME="$(basename "${DEP_FILE}")"
DEP_XML="${DEP_FILE}-tweaks"
VM_XML="${TMPDIR}/vm.xml"

cp -f "${DEP_FILE}" "${DEP_XML}"

oneCallXml onevm show "${VM_ID}" "${VM_XML}"
RET=$?
if [[ ${RET} -ne 0 ]]; then
    error_message "[E][deploy-tweaks] Error: Can't query VM ${VM_ID} (${TM_MAD},${DEPLOY_ID})"
    exit "${_RET}"
fi

declare -a _XPATH_A _XPATH_QUERY
_XPATH_A=(
    "${SCRIPT_PATH}/../../datastore/xpath.rb"
    "--stdin"
)
_XPATH_QUERY=(
    "/VM/DEPLOY_ID"
    "/VM/HISTORY_RECORDS/HISTORY[last()]/TM_MAD"
    "/VM/HISTORY_RECORDS/HISTORY[last()]/DS_ID"
)

sed '/\/>$/d' "${VM_XML}" >"${TMPDIR}/vmX.xml"
unset i XPATH_ELEMENTS
while IFS='' read -r -u "${xfh}" -d '' element; do
    XPATH_ELEMENTS[i++]="${element}"
done {xfh}< <("${_XPATH_A[@]}" <"${TMPDIR}/vmX.xml" "${_XPATH_QUERY[@]}" || true)
exec {xfh}<&-
unset i
DEPLOY_ID="${XPATH_ELEMENTS[i++]}"
TM_MAD="${XPATH_ELEMENTS[i++]}"
DS_ID="${XPATH_ELEMENTS[i++]}"

if [[ -z "${DS_ID}" ]]; then
    error_message "[E][deploy-tweaks] Can't get SYSTEM datastore ID for one-${VM_ID} (${TM_MAD},${DEPLOY_ID})"
    cat "${ERR_FILE}" >&2
    exit 255
fi

if [[ -d "${0}.d" ]]; then
    while read -r -u "${dtfh}" hook; do
        [[ -x  "${hook}" ]] || continue
        cp -f "${DEP_XML}" "${TMPDIR}/deployment.xml"
        ret=$?
        if [[ -n "${DEBUG_DEPLOY_TWEAKS}" ]]; then
            splog "[D] cp -f ${DEP_XML} ${TMPDIR}/deployment.xml (${ret})"
            splog "[D] Calling ${hook} ${TMPDIR}/deployment.xml ${TMPDIR}/vm.xml ..."
        fi
        "${hook}" "${TMPDIR}/deployment.xml" "${TMPDIR}/vm.xml" 2>"${ERR_FILE}"
        ret=$?
        splog "[I] ${hook} (${ret})"
        if [[ -n "${DEBUG_DEPLOY_TWEAKS}" ]]; then
            while read -r -u "${errfh}" errline; do
                splog "[D] stderr:${errline} //${hook}"
            done {errfh}< <(cat "${ERR_FILE}" || true)
            exec {errfh}<&-
            if [[ -n "${DDEBUG_DEPLOY_TWEAKS}" ]]; then
                cp "${TMPDIR}/deployment.xml" "/tmp/deployment-${hook##*/}.xml"
                cp "${TMPDIR}/vm.xml" "/tmp/vm-${hook##*/}.xml"
            fi
        fi
        if [[ ${ret} -eq 0 ]]; then
            xmllint --noout "${TMPDIR}/deployment.xml" 2>"${ERR_FILE}"
            ret=$?
            if [[ ${ret} -eq 0 ]]; then
                mv -f "${TMPDIR}/deployment.xml" "${DEP_XML}"
                continue
            else
                splog "[W] Error: ${hook} succeeded but xmllint failed with exit code ${ret}"
            fi
        else
            splog "[W] ${hook} failed with exit code ${ret}"
        fi
        if [[ -z "${DEBUG_DEPLOY_TWEAKS}" ]]; then
            while read -r -u "${errfd}" errline; do
                splog "[W] stderr:${errline}"
            done {errfd}< <(cat "${ERR_FILE}" || true)
            exec {errfd}<&-
        fi
    done {dtfh}< <(find "${0}.d/" -type f -o -type l || true)
    exec {dtfh}<&-
else
    splog "[W] Directory ${0}.d not found!"
fi

splog "[I] Sending ${DEP_XML} to ${HOST} for ${DATASTORE_LOCATION:-/var/lib/one/datastores}/${DS_ID}/${VM_ID}/${DEP_NAME} ..."
DOMAIN_ID="$(${SSH:-ssh} "${HOST}" "\"${SCRIPTS_REMOTE_DIR:-/var/tmp/one}/vmm/kvm/deploy\" \"${DATASTORE_LOCATION:-/var/lib/one/datastores}/${DS_ID}/${VM_ID}/${DEP_NAME}\"" < "${DEP_XML}" 2>>"${ERR_FILE}")"
ret=$?
splog "VM ${VM_ID} deploy on ${HOST} DOMAIN_ID=${DOMAIN_ID} (${ret})"

if [[ ${ret} -eq 0 ]]; then
    echo "${DOMAIN_ID}"
else
    error_message "[deploy-tweaks] VM ${VM_ID} could not create domain from ${DEP_FILE}"
    cat "${ERR_FILE}" >&2
    exit 255
fi
