#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# snapshot_create  domain snap_id vm_id vmhost
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get snapshot_create arguments from OpenNebula core
#-------------------------------------------------------------------------------

DOMAIN="$1"
SNAP_ID="$2"
VM_ID="$3"
VMHOST="$4"

DRIVER_PATH="$(dirname "$0")"
VMSNAPSHOT_TAG="ONESNAP"
VMSNAPSHOT_OVERRIDE=1

if [[ -f "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" ]]; then
    # shellcheck source=/dev/null
    source "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc"
else
    # shellcheck source=/dev/null
    source "${DRIVER_PATH}/kvmrc"
fi
# shellcheck source=/dev/null
source "${DRIVER_PATH}/../../scripts_common.sh"
# shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"

export LOG_PREFIX="vmm"

function getVmDomxml() {
    local _DOMAIN="$1" _VMHOST="$2"
    local _rCMD=""
    _rCMD=$(cat <<EOF
    [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
    virsh --connect \${LIBVIRT_URI:-qemu:///system} dumpxml "${_DOMAIN}"
EOF
)
    if [[ -z "${DOMXML}" ]]; then
        DOMXML="$(${SSH:-ssh} "${_VMHOST}" "${_rCMD}")"
        export DOMXML
    fi
}

splog "${DOMAIN} ${SNAP_ID} ${VM_ID} ${VMHOST}"

if boolTrue "VMSNAPSHOT_OVERRIDE"; then
    oneVmVolumes "${VM_ID}"
    oneDatastoreInfo "${VM_DS_ID}"

    splog "vmDisks:${vmDisks} vmVolumes:'${vmVolumes}'"
    if [[ -n ${oneVmVolumesShareable} ]]; then
        res="VM Snapshot of shareable disk is not supported!(${oneVmVolumesShareable})"
        error_message "${res}"
        splog "${res} (exit 1)"
        exit 1
    fi
    if boolTrue "VMSNAPSHOT_ENABLE_LIMIT"; then
        if [[ -n "${VM_VMSNAPSHOT_LIMIT}" ]]; then
            VMSNAPSHOT_LIMIT="${VM_VMSNAPSHOT_LIMIT}"
        fi
        if [[ -n "${VMSNAPSHOT_LIMIT}" ]]; then
            if [[ -z "${VMSNAPSHOT_LIMIT//[[:digit:]]}" ]]; then
                if [[ ${VMSNAPSHOT_LIMIT} -lt ${#SNAPSHOT_ID_A[@]} ]]; then
                    res="VMSNAPSHOT_LIMIT of ${VMSNAPSHOT_LIMIT} snaphosts exceeded!"
                    splog "${res}"
                    error_message "${res}"
                    exit 1
                else
                    res="VM snapshots limit VMSNAPSHOT_LIMIT:${VMSNAPSHOT_LIMIT} >= ${#SNAPSHOT_ID_A[@]}"
                    splog "${res}"
                    log "${res}"
                fi
            else
                res="Error: VMSNAPSHOT_LIMIT='${VMSNAPSHOT_LIMIT}' Not a number"
                splog "${res}"
                error_message "${res}"
                exit 1
            fi
        fi
    fi
    ts=$(date +%s)
    snap_name="${VMSNAPSHOT_TAG}-${SNAP_ID}-${ts}"
    snapjson=""
    for volume in ${vmVolumes}; do
        sp_uid=$(kvGet "byName" "${volume}")
        snap="${volume}-${snap_name}"
        #list+=("${volume}" "${snap}")
        [[ -z "${snapjson}" ]] || snapjson+=","
        snaptags="$(tagsHelper "snap;img;${VM_TAG};${LOC_TAG};virt" "${snap_name};${volume};${VM_ID};${LOC_TAG_VAL};one")"
        snapjson+="{\"volume\":\"${sp_uid}\",\"tags\":{${snaptags}},\"name\":\"\"}"
    done
    if boolTrue "VMSNAPSHOT_FSFREEZE"; then
        rCMD=$(cat <<EOF
    PARENTPID=\$PPID
    #echo "${DOMAIN}"
    [ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
    trap 'virsh --connect '\$LIBVIRT_URI' qemu-agent-command "'${DOMAIN}'" "{\"execute\":\"guest-fsfreeze-thaw\"}" 2>&1 >/dev/null ;\
    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsthaw '${DOMAIN}' ret:\$? \$(date +%s.%N) trap"' EXIT QUIT TERM INT HUP
    virsh --connect \$LIBVIRT_URI qemu-agent-command "${DOMAIN}" "{\"execute\":\"guest-fsfreeze-freeze\"}" 2>&1 >/dev/null
    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsfreeze ${DOMAIN} ret:\$? \$(date +%s.%N)"
    while [[ -d /proc/\$PARENTPID ]]; do
        logger -t "vmm_sp_snapshot_create_r[\$\$]" "${DOMAIN} \$(virsh --connect \$LIBVIRT_URI qemu-agent-command "${DOMAIN}" "{\"execute\":\"guest-fsfreeze-status\"}") \$(date +%s.%N)"
        sleep ${VMSNAPSHOT_SLEEP_REMOTE:-.1}
    done
    virsh --connect \$LIBVIRT_URI qemu-agent-command "${DOMAIN}" "{\"execute\":\"guest-fsfreeze-thaw\"}" 2>&1 >/dev/null
    logger -t "vmm_sp_snapshot_create_r[\$\$]" "fsthaw ${DOMAIN} ret:\$? \$(date +%s.%N)"
    logger -t "vmm_sp_snapshot_create_r[\$\$]" \$(virsh --connect \$LIBVIRT_URI qemu-agent-command "${DOMAIN}" "{\"execute\":\"guest-fsfreeze-status\"}") \$(date +%s.%N)
    #trap - TERM INT QUIT HUP
EOF
)
        trapAdd "trap - SIGTERM && kill -- -\$\$"
        ${SSH:-ssh} "${VMHOST}" "${rCMD}" 2>/dev/null >/dev/null &
        splog "VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN} is frosen"
        sleep "${VMSNAPSHOT_SLEEP:-.3}"
    fi
    if boolTrue "MULTICLUSTER"; then
        oneHostInfo "${VMHOST}"
        DO_REMOTE="~${HOST_SP_CLUSTER_ID}"
    fi

    if [[ -n "${TPM_MODEL}" ]]; then
        if boolTrue "ONE_TPM_SAVE"; then
            getVmDomxml "${DOMAIN}" "${VMHOST}"
            backendType="$(echo "${DOMXML}" |
                xmlstarlet sel -t -v domain/devices/tpm/backend/@type)"
            if [[ "${backendType}" == "emulator" ]]; then
                VM_PATH="$(echo "${DOMXML}" | \
                    xmlstarlet sel -N one="http://opennebula.org/xmlns/libvirt/1.0" \
                    -t -v '//one:vm/one:system_datastore/text()')"
                oneTpmBackup "${VM_ID}" "${VM_PATH}" "${VMHOST}"
                tpmSave "${VM_ID}" "${VM_PATH}" "${VMHOST}"
                _SP_VOL="${ONE_PX}-sys-${VM_ID}-SWTPM"
                [[ -z "${snapjson}" ]] || snapjson+=","
                snaptags="$(tagsHelper "snap;img;${VM_TAG};${LOC_TAG};virt;type" "${snap_name};${_SP_VOL};${VM_ID};${LOC_TAG_VAL};one;SWTPM")"
                snapjson+="{\"volume\":\"${SP_UID}\",\"tags\":{${snaptags}},\"name\":\"\"}"
            fi
        else
            errmsg="VM ${VM_ID} TPM_MODEL=${TPM_MODEL}, butONE_TPM_SAVE is not enabled in addon-storpoolrc"
            splog "${errmsg}"
            error_message "${errmsg}"
            exit 1
        fi
    fi

    tags="$(tagsHelper "virt;${VM_TAG};${LOC_TAG}" "one;${VM_ID};${LOC_TAG_VAL}")"
    json="\"volumes\":[${snapjson}],\"tags\":{${tags}}"
    snapshots="$(storpoolRetry VolumesGroupSnapshot "${json}")"
    ret=$?
    if [[ ${ret} -eq 0 ]]; then
        while read -r -u 5 name snapshot_globalid; do
            vname="$(echo "{${json}}" | jq -r --arg volume "${name}" \
                        '.volumes[]|select(.volume==$volume)|"\(.tags.img)-\(.tags.snap)"')"
            kvPut "${vname}" "~${snapshot_globalid}"
        done 5< <(echo "${snapshots}" | jq -r '.data.snapshots[]|"\(.volume) \(.snapshotGlobalId)"' || true)
    fi
    if boolTrue "VMSNAPSHOT_FSFREEZE"; then
        declare -a pids_a
        unset i
        while read -r -u "${jfh}" pid; do
            pids_a[i++]="${pid}"
        done {jfh}< <(jobs -p || true)
        if [[ ${#pids_a[*]} -gt 0 ]]; then
            kill "${pids_a[@]}" 2>/dev/null >/dev/null
            ret=$?
            splog "kill ${pids_a[*]} (${ret})"
            if [[ ${ret} -eq 0 ]]; then
                splog "VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN} is thawed"
                trapReset
            else
                splog "Unable to kill the process holding the VM with freezed filesystem VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN}"
            fi
        fi
    fi
    echo "${snap_name}"
    splog "END VM_ID=${VM_ID} VMHOST=${VMHOST} SNAP_ID=${SNAP_ID} suffix:${res}"
    exit 0
else
    res="VMSNAPSHOT_OVERRIDE is not set"
    splog "[E] ${res}"
    error_message "${res}"
    exit 1
fi
