#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# snapshot_revert  domain snap_id vm_id vmhost
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get snapshot_revert arguments from OpenNebula core
#-------------------------------------------------------------------------------

DOMAIN="$1"
SNAP_ID="$2"
VM_ID="$3"
VMHOST="$4"

DRIVER_PATH="$(dirname "$0")"
VMSNAPSHOT_TAG="ONESNAP"
VMSNAPSHOT_OVERRIDE=1
#DS_PATH="/var/lib/one/datastores"

if [[ -f "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc" ]]; then
    # shellcheck source=/dev/null
    source "${DRIVER_PATH}/../../etc/vmm/kvm/kvmrc"
else
    # shellcheck source=/dev/null
    source "${DRIVER_PATH}/kvmrc"
fi
# shellcheck source=/dev/null
source "${DRIVER_PATH}/../../scripts_common.sh"
# shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"

export LOG_PREFIX="vmm"

if boolTrue "DEBUG_VMSNAPSHOT"; then
    splog "[D] $0 $*"
fi

if boolTrue "VMSNAPSHOT_OVERRIDE"; then
    oneVmVolumes "${VM_ID}"
    oneDatastoreInfo "${VM_DS_ID}"

#    declare -A vmDisks_a diskVolumes vmVolumesQcMap vmDisksReadOnly_a vmDisksType_a
#    for entry in ${vmVolumes}; do
#        diskVolumes["${entry}"]="${entry}"  # diskVolumes[oneName]=oneName
#    done
#    for entry in ${vmDisksMap}; do
#        vmDisks_a["${entry%:*}"]="${entry##*:}"  # vmDisks_a[oneName]=DISK_ID
#    done
#    for entry in ${vmDisksReadOnlyMap}; do
#        vmDisksReadOnly_a["${entry%:*}"]="${entry##*:}"  # vmDisksReadOnly_a[oneName]=READONLY
#    done
#    for entry in ${vmVolumesQc:-}; do
#        vmVolumesQcMap["${entry%:*}"]="${entry##*:}"  # vmVolumesQcMap[oneName]=QOSCLASS
#    done
#    for entry in ${vmDisksTypeMap}; do
#        vmDisksType_a["${entry%:*}"]="${entry##*:}"  # vmDisksType_a[oneName]=xTYPE
#    done

    if boolTrue "MULTICLUSTER"; then
       oneHostInfo "${VMHOST}"
       DO_REMOTE="~${HOST_SP_CLUSTER_ID}"
    fi

    unset vmVolumesMap diskVolumes vmVolumesQcMap
    declare -A vmVolumes_a
    declare -A diskVolumes_a
    declare -A vmVolumesQc_a
    declare -A persistentDisksQc_a
    for volume in ${vmVolumes}; do
        vmVolumes_a["${volume}"]="${volume}"  # vmVolumes_a[VOLUME_NAME]=VOLUME_NAME
    done
    for disk in ${vmDisksMap}; do
        diskVolumes_a["${disk%:*}"]="${disk##*:}"  # diskVolumes_a[VOLUME_NAME]=DISK_ID
    done

    for volume in ${vmDisksQcMap}; do
        vmVolumesQc_a["${volume%%:*}"]="${volume##*:}"  # vmVolumesQc_a[VOLUME_NAME]=QOSCLASS
    done
    for volume in ${persistentDisksQcMap}; do
        persistentDisksQc_a["${volume%%:*}"]="${volume##*:}"  # persistentDisksQc_a[VOLUME_NAME]=QOSCLASS
    done

# TBD: check is needed
#    if boolTrue "VMSNAPSHOT_WITH_CHECKPOINT"; then
#        MEM_VOL="${ONE_PX}-sys-${VM_ID}"
#        diskVolumes["$MEM_VOL"]="$MEM_VOL3"
#    fi

    if [[ -n "${TPM_MODEL}" ]]; then
        SWTPM_VOL="${ONE_PX}-sys-${VM_ID}-SWTPM"
        vmVolumes_a["${SWTPM_VOL}"]="${SWTPM_VOL}"
        diskVolumes_a["${SWTPM_VOL}"]="tpm"
    fi

    export vmVolumes_a

    rCMD=$(cat <<EOF
    [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
	while read -r -u 4 out; do
        logger -t vmm_sp_snapshot_revert_r "VM ${VM_ID} virsh: \$out"
    done 4< <(virsh --connect "\$LIBVIRT_URI" destroy "${DOMAIN}" 2>&1)
    logger -t vmm_sp_snapshot_revert_r "VM ${VM_ID} virsh destroy ${DOMAIN} ret:\$?"
EOF
)
    if boolTrue "VMSNAPSHOT_RESTARTDOMAIN"; then
        restartDomainDirname="/var/lib/one/datastores/${VM_DS_ID}/${VM_ID}"
        restartDomain="${restartDomainDirname}/$(mktemp -u restart-XXXXXX).domain"
        rCMD=$(cat <<EOF
    [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
    mkdir -p "${restartDomainDirname}"
    virsh --connect "\$LIBVIRT_URI" dumpxml "${DOMAIN}" --inactive 2>"/tmp/sprevert-${VM_ID}-dumpxml.err" >"${restartDomain}"
    logger -t vmm_sp_snapshot_revert_r "VM ${VM_ID} virsh dumpxml ${DOMAIN} > "${restartDomain}" ret:\$?"
	while read -r -u 4 out; do
        logger -t vmm_sp_snapshot_revert_r "VM ${VM_ID} virsh: \$out"
    done 4< <(virsh --connect "\$LIBVIRT_URI" destroy "${DOMAIN}" 2>&1)
    logger -t vmm_sp_snapshot_revert_r "VM ${VM_ID} virsh destroy ${DOMAIN} ret:\$?"
EOF
)
    fi
    ${SSH:-ssh} "${VMHOST}" "${rCMD}" 2>"/tmp/sprevert-${VM_ID}-destroy.err" >"/tmp/sprevert-${VM_ID}-desctroy.out"
    splog "VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN} destroyed ($?)"
    sleep .5
    declare -a tmpVolumes_a=()
    declare -a snapList_a=()
    MEM_VOL="${ONE_PX}-sys-${VM_ID}"
    storpoolRetry SnapshotsList
    while read -r -u "${jqfh}" sp_uid img loctagval; do
        if boolTrue "DDEBUG_VMSNAPSHOT"; then
            splog "snapshot sp_uid:${sp_uid} tag img:${img} ${LOC_TAG}:${loctagval}"
        fi
        if [[ "${img}" == "${MEM_VOL}" ]]; then
            continue
        fi
        if [[ -z "${diskVolumes_a["${img}"]}" ]]; then
            if boolTrue "DEBUG_VMSNAPSHOT"; then
                splog "[D] VM ${VM_ID} Skip snapshot ${sp_uid} for ${img} (not in diskVolumes:${!diskVolumes_a[*]})"
            fi
            continue
        fi
        snapList_a+=("${sp_uid}-${img}-${SNAP_ID}")
    done {jqfh}< <(jq -r --arg snap_id "${SNAP_ID}" --arg vm_tag "${VM_TAG}" --arg vm_id "${VM_ID}" --arg loctag "${LOC_TAG}" \
                  '.data[]|select(.tags[$vm_tag]==$vm_id)|select(.tags["snap"]==$snap_id)|select(.deleted==false)|"\(.name) \(.tags["img"]|tostring) \(.tags[$loctag]|tostring)"' \
                  "${TMPDIR}/SnapshotsList.json" || true)
    exec {jqfh}<&-

    boolTrue "UPDATE_ONE_DISK_SIZE" && REVERT_SIZE=1 || REVERT_SIZE=0

    splog "snapList_a: [${snapList_a[*]}]"
    finish=1
    for snapentry in "${snapList_a[@]}"; do
        tb="$(date +%s%N)"
        splog "-=[B]=- snapshot ${snapentry} (${tb})"
        snapUid="${snapentry%%-*}"
        snap="${snapentry#*-}"
        volume="${snap%-"${SNAP_ID}"}"
        sp_uid=$(kvGet "byName" "${volume}")
        if [[ -z ${sp_uid} ]]; then
            splog "Can't get StorPool UID for ${volume} //next"
            finish=0
            continue
        fi
        [[ ${volume%-iso} == "${volume}" ]] && mode="rw" || mode="${READONLY_MODE}"

        VM_DISK_SP_QOSCLASS="${vmVolumesQc_a[${volume}]}"
        IMAGE_SP_QOSCLASS="${persistentDisksQc_a[${volume}]}"

        SP_QOSCLASS="${VM_DISK_SP_QOSCLASS:-${IMAGE_SP_QOSCLASS:-${VM_SP_QOSCLASS:-${DS_SP_QOSCLASS:-${DEFAULT_QOSCLASS}}}}}"
        debug_sp_qosclass

        if boolTrue "DDEBUG_VMSNAPSHOT"; then
            splog "[DD] volume ${sp_uid}::${volume} snapshot ${snapUid}::${snap} ${mode}"
        fi
        storpoolDetach "${sp_uid}" "force" "${VMHOST}" "all"
        storpoolVolumeInfo "${sp_uid}"
        if [[ "${V_TYPE}" == "CDROM" ]]; then
            mode="${READONLY_MODE}"
        fi
        storpoolVolumeRevert "${sp_uid}" "${volume}" "${snapUid}" "${REMOTE_BACKUP_DELETE}" "${REVERT_SIZE}" || finish=0
        if booltTrue "REVERT_SEZE"; then
            OLD_SIZE_M=$((V_SIZE/1024/1024))
            storpoolVolumeInfo "~${SP_GLOBALID}"
            NEW_SIZE_M=$((V_SIZE/1024/1024))
            if [[ ${OLD_SIZE_M} -ne ${NEW_SIZE_M} ]]; then
                if [[ -n "${diskVolumes_a["${volume}"]}" ]]; then
                    DISK_ID="${diskVolumes_a[${volume}]}"
                    onedb change-body vm --id "${VM_ID}" "/VM/TEMPLATE/DISK[DISK_ID=${DISK_ID}]/SIZE" "${NEW_SIZE_M}"
                    splog "[I] onedb change VM_ID:${VM_ID} DISK_ID:${DISK_ID} SIZE:${NEW_SIZE_M} (OLD_SIZE:${OLD_SIZE_M}) ($?)"
                else
                    splog "[W] diskVolumes_a[${volume}] not found"
                fi
            else
                splog "[I] (old size:${OLD_SIZE_M}) == (${volume}:${NEW_SIZE_M}) sp_uid:${sp_uid}"
            fi
        fi
        storpoolAttach "${sp_uid}" "${VMHOST}" "${mode}"
#        SYMLINK="/var/lib/one/datastores/${VM_DS_ID}/${VM_ID}/disk.${vmVolumesMap["${volume}"]}"
#        oneSymlink "${VMHOST}" "${sp_uid}" "${SYMLINK}" || finish=0

        storpoolVolumeTag "${sp_uid}" \
            "virt;${LOC_TAG};diskid;${VM_TAG};${VC_POLICY:+vc-policy};${SP_QOSCLASS:+qc}" \
             "one;${LOC_TAG_VAL};${diskVolumes_a["${volume}"]};${VM_ID};${VC_POLICY};${SP_QOSCLASS}"
        te="$(date +%s%N)"
        splog "-=[E]=- snapshot ${snapentry} (${te} dt:$((te-tb)))"
    done
    if boolTrue "finish" "${finish}"; then # make shellcheck happy
        for volume in "${tmpVolumes_a[@]}"; do
            sp_uid="${volume%%-*}"
            sp_uid="${sp_uid#*~}"
            vname="${volume#*-}"
            splog "-=[F]=- ${volume}: sp_uid ${sp_uid} volume ${vname}"
            storpoolDelete "${sp_uid}" "force" "" "" "\"vname\":\"${vname}\",\"reason\":\"snapshot_revert\""
            kvDelByKey "/byUid/${sp_uid}"
            kvDelByKey "/byName/${vname}"
        done
    fi
    if boolTrue "VMSNAPSHOT_RESTARTDOMAIN"; then
        rCMD=$(cat <<EOF
    [[ -f "/var/tmp/one/etc/vmm/kvm/kvmrc" ]] && source "/var/tmp/one/etc/vmm/kvm/kvmrc" || source "/var/tmp/one/vmm/kvm/kvmrc"
    virsh --connect "\$LIBVIRT_URI" create "${restartDomain}" && rm -f "${restartDomain}" "/tmp/sprevert-${VM_ID}"*
    logger -t vmm_sp_snapshot_revert_r "VM ${VM_ID} virsh create ${restartDomain} //${DOMAIN}  ret:\$?"
EOF
)
        ${SSH:-ssh} "${VMHOST}" "${rCMD}" 2>"/tmp/sprevert-${VM_ID}-create.err" >"/tmp/sprevert-${VM_ID}-create.out"
        ret=$?
        if [[ ${ret} -eq 0 ]]; then
            splog "VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN} restarted XML:${restartDomain}"
            rm -f "/tmp/sprevert-${VM_ID}"*
        else
            splog "VM ${VM_ID} host:${VMHOST} DOMAIN_ID:${DOMAIN} XML:${restartDomain} failed to restart ${ret}"
        fi
    fi
    splog "END VM ${VM_ID} VMHOST=${VMHOST} SNAP_ID=${SNAP_ID}"
    exit 0
else
    splog "[CONTINUE] VM ${VM_ID}"
fi
