#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2024, StorPool (storpool.com)                               #
# Portions copyright Andrei 'kvaps' Kvapil (https://github.com/kvaps)        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

DRIVER_PATH=$(dirname $0)
ACTION=${0##*tm}
FILE=$1
HVHOST=$2
DEPLOY_ID=$3
VM_ID=$4

if [ "$ACTION" = "save" ]; then
    DEPLOY_ID=$1
    FILE=$2
    HVHOST=$3
    VM_ID=$4
    DS_ID=$5
fi

# There is data in stdin, read it
DRV_ACTION="$(cat)"

#-------------------------------------------------------------------------------

source $(dirname $0)/../../scripts_common.sh
source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"

LOG_PREFIX=vmm

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"
IFS= read -r -d '' TM_MAD < <(echo "$DRV_ACTION" | base64 -d | \
                               $XPATH /VMM_DRIVER_ACTION_DATA/DATASTORE/TM_MAD)

VMM_MAD="$(basename "$DRIVER_PATH")"
PRE_SCRIPT="${DRIVER_PATH}/../../tm/${TM_MAD}/pre${ACTION}"
POST_SCRIPT="${DRIVER_PATH}/../../tm/${TM_MAD}/post${ACTION}"

#-------------------------------------------------------------------------------

splog "$*"

# execute tm/prerestore if exist
if [ -f "$PRE_SCRIPT" ] && [ -x "$PRE_SCRIPT" ]; then
    splog "calling $PRE_SCRIPT $*"
    echo "$DRV_ACTION" | $PRE_SCRIPT "$@" || exit $?
fi

# execute vmm/save on remote host
echo "$DRV_ACTION" | \
       $SSH "$HVHOST" "/var/tmp/one/vmm/${VMM_MAD}/${ACTION}" "$@" || exit $?

# execute tm/postsave if exist
if [ -f "$POST_SCRIPT" ] && [ -x "$POST_SCRIPT" ]; then
    splog "calling $POST_SCRIPT $*"
    echo "$DRV_ACTION" | $POST_SCRIPT "$@" || exit $?
fi
splog "END $VM_ID"
exit 0
