#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2024, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

DRIVER_PATH=$(dirname $0)
LOG_PREFIX="ds"

source $DRIVER_PATH/../../scripts_common.sh
source ${DRIVER_PATH}/../../tm/storpool/storpool_common.sh

splog "$*"

cat >"/tmp/${0##*/}-$3-$4-$5.input"

msg="${0##*/}: Operation not supported"
error_message "$msg"
splog "$msg"

splog "END"

exit 1
