#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# cp base64drvActionXML id
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Set up the environment to source common tools
#-------------------------------------------------------------------------------

if [[ -n "${ONE_LOCATION}" ]]; then
    LIB_LOCATION="${ONE_LOCATION}/lib"
else
    LIB_LOCATION="/usr/lib/one"
fi
# shellcheck source=/dev/null
source "${LIB_LOCATION}/sh/scripts_common.sh"

DRIVER_PATH="$(dirname "$0")"
# shellcheck source=/dev/null
source "${DRIVER_PATH}/../libfs.sh"

# shellcheck source=/dev/null
source "${DRIVER_PATH}/../libfs.sh"

# shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"

export LOG_PREFIX="ds"

if boolTrue "DS_CP_REPORT_FORMAT"; then
    REPORT_FORMAT=raw
    UPDATE_IMAGE_ON_IMPORT=0
else
    REPORT_FORMAT=""
fi

#-------------------------------------------------------------------------------
# Get cp and datastore arguments from OpenNebula core
#-------------------------------------------------------------------------------

if [[ -n "$2" ]]; then
    export DRV_ACTION="$1"
    ID="$2"
else
    DRV_ACTION="$(cat)"
    export DRV_ACTION
    ID="$1"
fi

#echo "cd ${PWD}; bash -x $0 $*" >"/tmp/cp-$ID"

oneDsDriverAction

#-------------------------------------------------------------------------------
# Validate variables
#-------------------------------------------------------------------------------

if [[ -n "${BRIDGE_LIST}" ]]; then
    DST_HOST="$(get_destination_host "${ID}")"
    if [[ -z "${DST_HOST}" ]]; then
        error_message "Datastore template missing 'BRIDGE_LIST' attribute."
        exit 255
    fi
fi

set_up_datastore "${BASE_PATH:-/var/lib/one/datastores}" "${RESTRICTED_DIRS:-/etc}" "${SAFE_DIRS:-/var/tmp}"

# shellcheck disable=SC2116
IMAGE_PATH="$(echo "${IMAGE_PATH}")" #TBD

case "${IMAGE_PATH}" in
*VMSNAP:*|*SPSNAPSHOT:*)
    oneSnapshotLookup "${IMAGE_PATH##*/}"
    log "Using StorPool snapshot '${IMAGE_PATH}'"
    ;;
http://*|https://*|ssh://*|s3://*|rbd://*|vcenter://*)
    log "Downloading ${IMAGE_PATH} to the image repository"
    ;;
rsync://*|restic://*)
    log "Downloading backup ${IMAGE_PATH} to the image repository"
    ;;
*)
    IS_RESTRICTED="$(check_restricted "${IMAGE_PATH}" || true)"
    if [[ ${IS_RESTRICTED:-1} -eq 1 ]]; then
        log_error "Not allowed to copy images from ${RESTRICTED_DIRS}"
        error_message "Not allowed to copy image file ${IMAGE_PATH}"
        exit 255
    fi

    log "Copying local image ${IMAGE_PATH} to the image repository"
    if [[ -z "${MD5}${SHA1}${NOLOCAL}" ]]; then
        # fix SC2001
        #localFile="$(echo "${IMAGE_PATH}" | sed -e "s/'/'\\\''/g")"
        replacement="'\''"
        localFile="${IMAGE_PATH//\'/${replacement}}"
        log "Using direct IO"
    else
        splog "${MD5:+MD5:${MD5} }${SHA1:+SHA1:${SHA1} }${NOLOCAL:+NOLOCAL:${NOLOCAL}}"
    fi
    ;;
esac

SP_VOL="${ONE_PX}-img-${ID}"
SP_TEMPLATE="${ONE_PX}-ds-${DATASTORE_ID:-}"
SP_DST="${SP_TEMPLATE}/${SP_VOL}"

storpoolVolumeCheck "${SP_VOL}" byName

if [[ -n "${SNAPSHOT_NAME}" ]]; then

    if [[ ${IMAGE_GID:-65536} -ne 0 ]]; then
        if [[ ${VM_UID:-65536} -ne ${IMAGE_UID:-65536} ]]; then
            errmsg="UID ${IMAGE_UID} is not allowed to import snapshot from VM with UID:${VM_UID}"
            log_error "${errmsg}"
            error_message "${errmsg}"
            splog "${errmsg}"
            exit 255
        fi
    fi

    msg="UID ${IMAGE_UID} with GID:${IMAGE_GID} imported ${SNAPSHOT_NAME} (VMUID:${VM_UID}) as ${SP_DST}"
    log "${msg}"
    splog "${msg}"
    if kvGetUid "${SNAPSHOT_NAME}"; then
        ENTRY="${SP_UID}"
    else
        ENTRY="${SNAPSHOT_NAME}"
        storpoolExist "${SNAPSHOT_NAME}" "Snapshot"
    fi
    if ! storpoolSnapshotInfo "${ENTRY}"; then
        errmsg="Error: Can't get Storpool info for snapshot '${ENTRY}' ($?)"
        log_error "${errmsg}"
        error_message "${errmsg}"
        splog "${errmsg}"
        exit 255
    fi
    if [[ "${ENTRY:0:1}" == "~" ]]; then
        SP_UID="${ENTRY}"
    else
        SP_UID="~${X_GLOBALID}"
    fi

    SNAPSHOT_UID="${SP_UID}"
    storpoolVolumeFromSnapshot "${SNAPSHOT_UID}" "${SP_VOL}"

    VOL_UID="${SP_UID}"
    FORMAT="raw"

    echo "${SP_DST} ${REPORT_FORMAT}"

else

    SP_TEMP_VOL="${SP_VOL}-$(echo "${SP_VOL}" | md5sum | awk '{print $1}')"
    CREATE_SIZE="$((SIZE*1024*1024))"
    TEMP_SIZE="${CREATE_SIZE}"

    CREATE_SIZE="$((SIZE*1024*1024))"
    TEMP_SIZE="${CREATE_SIZE}"
    if [[ -z "${SIZE}" ]] || [[ ${SIZE} -eq 0 ]]; then
        TEMP_SIZE=$((1*1024*1024))
    else
        qemu_img_info "${IMAGE_PATH}"
        if [[ -n "${STAT_IMAGE_SIZE}" ]] && [[ ${STAT_IMAGE_SIZE} -gt 0 ]]; then
            if [[ "${QEMU_IMG_FORMAT}" != "raw" ]]; then
                # use the actual file size
                TEMP_SIZE="${STAT_IMAGE_SIZE}"
                splog "[I] File ${IMAGE_PATH}, FORMAT:${QEMU_IMG_FORMAT} using actual file size: ${STAT_IMAGE_SIZE}"
            else
                # Check is the imported file size is bigger than the virtual size
                FSIZE=$(((STAT_IMAGE_SIZE+1048575)/1048576))
                if [[ ${FSIZE} -gt ${SIZE} ]]; then
                    splog "[W] File ${IMAGE_PATH} stat size ${FSIZE}(${STAT_IMAGE_SIZE}) <> SIZE=${SIZE} (with ~ $((FSIZE-SIZE))MB)"
                    TEMP_SIZE="$((FSIZE*1024*1024))"
                    CREATE_SIZE="${TEMP_SIZE}"
                fi
            fi
        fi
    fi

    storpoolVolumeCreate "${SP_TEMP_VOL}" "${TEMP_SIZE}" "${SP_TEMPLATE}"

    if [[ -z "${SP_UID}" ]]; then
        errmsg="Error: Can't create ${SP_TEMP_VOL} (no StorPool UID) SIZE:${TEMP_SIZE}"
        log_error "${errmsg}"
        error_message "${errmsg}"
        splog "${errmsg}"
        exit 1
    fi

    TEMP_VOL_UID="${SP_UID}"
    SP_TEMP_LINK="/dev/storpool-byid/${TEMP_VOL_UID#*~}"

    echo "${SP_DST} ${REPORT_FORMAT}"

    if [[ -n "${SP_IMPORT_CGROUPS}" ]]; then
        set -o pipefail
        for cg in ${SP_IMPORT_CGROUPS}; do
            [[ "${cg/../}" == "${cg}" ]] || continue
            [[ -d "/sys/fs/cgroup/${cg}" ]] || continue
            echo "$$" | ${SUDO:-sudo} tee "/sys/fs/cgroup/${cg}/tasks" >/dev/null
            splog "($?) pin PID $$ to cgroup ${cg}/tasks"
        done
    fi

    trapAdd "storpoolDelete \"${TEMP_VOL_UID}\" force snaps"

    storpoolAttach "${TEMP_VOL_UID}" "${DST_HOST}"

    if [[ -n "${DST_HOST}" ]]; then
        DOWNLOADER_ARGS="$(set_downloader_args "${MD5}" "${SHA1}" "${NO_DECOMPRESS:-}" "${LIMIT_TRANSFER_BW:-}" "${IMAGE_PATH}" -)"
    else
        DOWNLOADER_ARGS="$(set_downloader_args "${MD5}" "${SHA1}" "${NO_DECOMPRESS:-}" "${LIMIT_TRANSFER_BW:-}" "${IMAGE_PATH}" "${SP_TEMP_LINK}")"
    fi

    COPY_CMD="${DRIVER_PATH}/../downloader.sh ${DOWNLOADER_ARGS}"

    if [[ -z "${SIZE}" ]] || [[ ${SIZE} -eq 0 ]]; then
        localFile="/var/tmp/${SP_TEMP_VOL}"
        splog "image SIZE=${SIZE} downloading on fe to get the size"
        DOWNLOADER_ARGS="$(set_downloader_args "${MD5}" "${SHA1}" "${NO_DECOMPRESS}" "${LIMIT_TRANSFER_BW}" "${IMAGE_PATH}" "${localFile}")"
        COPY_CMD="${DRIVER_PATH}/../downloader.sh ${DOWNLOADER_ARGS}"
        splog "COPY_CMD='${COPY_CMD}'"
        multiline_exec_and_log "${COPY_CMD}" \
                     "Error dumping ${IMAGE_PATH} to ${localFile}"
        SIZE="$(fs_size "${localFile}" "${NO_DECOMPRESS}" "${LIMIT_TRANSFER_BW}")"

        storpoolVolumeResize "${TEMP_VOL_UID}" "$((SIZE*1024*1024))"

        splog "${TEMP_VOL_UID} image ${localFile} SIZE=${SIZE} (M)"

        CLEANUP="${localFile}"
    fi
    #-------------------------------------------------------------------------------
    # Import image to a temporary volume
    #-------------------------------------------------------------------------------

    tStart=$(date +%s)
    if [[ -n "${DST_HOST}" ]]; then
        if [[ -n "${localFile}" ]] && [[ -f "${localFile}" ]]; then
            COPY_CMD="${DD:-dd} if=\"${localFile}\" bs=\"${COPY_CMD_DS_BS:-1M}\" iflag=direct"
        fi
        splog "eval ${COPY_CMD//&/\\&} | ${SSH:-ssh} ${DST_HOST} ${DD:-dd} of=${SP_TEMP_LINK} bs=${COPY_CMD_DD_BS:-1M} status=none iflag=fullblock oflag=direct"
        multiline_exec_and_log "set -e -o pipefail; eval ${COPY_CMD//&/\\&} | ${SSH:-ssh} \"${DST_HOST}\" ${DD:-dd} of=\"${SP_TEMP_LINK}\" bs=\"${COPY_CMD_DD_BS:-1M}\" status=none iflag=fullblock oflag=direct" \
                     "Error dumping ${IMAGE_PATH} to ${DST_HOST}:${SP_TEMP_LINK}"
    else
        if [[ -n "${localFile}" ]] && [[ -f "${localFile}" ]]; then
            COPY_CMD="${DD:-dd} if=\"${localFile}\" of=\"${SP_TEMP_LINK}\" bs=\"${COPY_CMD_DD_BS:-1M}\" iflag=direct oflag=direct"
        fi
        splog "COPY_CMD='${COPY_CMD}'"
        multiline_exec_and_log "${COPY_CMD}" \
                     "Error dumping ${IMAGE_PATH} to ${SP_TEMP_VOL}"
    fi
    tEnd="$(date +%s)"
    tEnd=$((tEnd - tStart))
    [[ ${tEnd} -ne 0 ]] || tEnd=1
    splog "image transferred in ${tEnd} seconds (~$((SIZE/tEnd))MB/s)"

    if [[ -n "${CLEANUP}" ]]; then
        rm -f "${localFile}"
        splog "cleanup temp file ${localFile} ($?)"
    fi

    #-------------------------------------------------------------------------------
    # Process imported image
    #-------------------------------------------------------------------------------

    qemu_img_info "${SP_TEMP_LINK}" "${DST_HOST}"
    FORMAT="${QEMU_IMG_FORMAT}"

    if [[ "${FORMAT}" != "${DRIVER:-undefined}" ]]; then
        splog "${QEMU_IMG} detected format '${FORMAT}' but DRIVER=${DRIVER} in the image template"
    fi

    if [[ "${FORMAT}" == "raw" ]]; then

        storpoolDetach "${TEMP_VOL_UID}" "force" "${DST_HOST}"

        storpoolVolumeRename "${TEMP_VOL_UID}" "${SP_TEMP_VOL}" "${SP_VOL}" "${SP_TEMPLATE}"
        VOL_UID="${TEMP_VOL_UID}"
    else
        storpoolVolumeCreate "${SP_VOL}" "${CREATE_SIZE}" "${SP_TEMPLATE}"

        if [[ -z "${SP_UID}" ]]; then
            splog "Can't create volume ${SP_VOL} size ${CREATE_SIZE} template ${SP_TEMPLATE}"
            exit 1
        fi
        VOL_UID="${SP_UID}"
        SP_LINK="/dev/storpool-byid/${VOL_UID#*~}"

        trapAdd "storpoolDelete \"${VOL_UID}\" force snaps"

        storpoolAttach "${VOL_UID}" "${DST_HOST}"

        POST_COPY_CMD=$(cat <<EOF
    set -e
    export PATH=/bin:/sbin:/usr/bin:/usr/sbin:\$PATH
    splog(){ logger -t "ds_sp_${0##*/}[\$\$]" "\$*"; }

    splog "${FORMAT} ${QEMU_IMG:-qemu-img} convert -t none -T none -O raw -S 4k ${SP_TEMP_LINK} ${SP_LINK}"
    ${QEMU_IMG:-qemu-img} convert -t none -T none -O raw -S 4k "${SP_TEMP_LINK}" "${SP_LINK}"
    sync
EOF
)
        tStart=$(date +%s)
        if [[ -n "${DST_HOST}" ]]; then
            splog "convert from ${FORMAT} to raw at ${DST_HOST}"
            ssh_exec_and_log "${DST_HOST}" "${POST_COPY_CMD}" \
                             "Error converting image on ${DST_HOST}"
        else
            splog "${FORMAT} ${QEMU_IMG:-qemu-img} convert -t none -T none -O raw -S 4k ${SP_TEMP_LINK} ${SP_LINK}"
            ${QEMU_IMG:-qemu-img} convert -t none -T none -O raw -S 4k "${SP_TEMP_LINK}" "${SP_LINK}"
            sync
        fi
        tEnd=$(date +%s)
        splog "image converted to raw in $((tEnd-tStart)) seconds"

        trapDel "storpoolDelete \"${VOL_UID}\" force snaps"

        storpoolDetach "${TEMP_VOL_UID}" "" "${DST_HOST}"

        trapDel "storpoolDelete \"${TEMP_VOL_UID}\" force snaps"

        DELAY_DELETE="" storpoolDelete "${TEMP_VOL_UID}" "force" "snaps"

        storpoolDetach "${VOL_UID}" "force" "${DST_HOST}"
    fi
fi

SP_QOSCLASS="${IMAGE_SP_QOSCLASS:-${DS_SP_QOSCLASS:-${DEFAULT_QOSCLASS}}}"
debug_sp_qosclass

storpoolVolumeTag "${VOL_UID}" "virt;${LOC_TAG:-nloc};img;qc" "one;${LOC_TAG_VAL:-};${SP_VOL};${SP_QOSCLASS}"

storpoolVolumeFreeze "${VOL_UID}" "volume"
ret=$?
if [[ ${ret} -ne 0 ]]; then
    splog "Error: Volume to snapshot conversion failed! (${ret})"
    exit "${ret}"
fi

#-------------------------------------------------------------------------------
# fix image DRIVER to raw
#-------------------------------------------------------------------------------

if [[ "${DRIVER}" != "raw" ]]; then
    if boolTrue "UPDATE_IMAGE_ON_IMPORT"; then
        splog "image template DRIVER=${DRIVER} updating to DRIVER=raw"
        TMP_XML="${TMPDIR}/image-template"
        echo "DRIVER=raw" >"${TMP_XML}"
        echo "FORMAT=raw" >>"${TMP_XML}"
        if [[ -n "${DS_CP_FORCE_DEV_PREFIX}" ]]; then
            echo "DEV_PREFIX=${DS_CP_FORCE_DEV_PREFIX}" >>"${TMP_XML}"
        fi
        oneimage update -a "${ID}" "${TMP_XML}" 2>"${TMPDIR}/oneimage-update-err" >"${TMPDIR}/oneimage-update-out"
        ret=$?
        if [[ ${ret} -ne 0 ]]; then
            if grep -qir "${UPDATE_IMAGE_LOCK_STRING:-locked}" "${TMPDIR}" 2>/dev/null; then
                splog "(${ret}) oneimage update ${ID} ... Re-trying with unlock"
                oneimage unlock "${ID}"
                splog "($?) oneimage unlock ${ID}"
                oneimage update -a "${ID}" "${TMP_XML}"
                splog "($?) oneimage update ${ID}"
                oneimage lock "${ID}"
                splog "($?) oneimage lock ${ID}"
            else
                splog "(${ret}) oneimage update -a ${ID} ... Failed!"
            fi
        fi

    elif [[ -z "${REPORT_FORMAT}" ]]; then
        splog "image template DRIVER='${DRIVER}' and FORMAT='${FORMAT}' but image update is not enabled."
    fi
fi

trapReset

splog "END:${SP_DST}${REPORT_FORMAT:+ ${REPORT_FORMAT}}"
