#!/bin/bash
#

# -------------------------------------------------------------------------- #
# Copyright 2015-2016, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

function splog() { logger -t "ds_sp_${0##*/}" "$*"; }

DRV_ACTION="$1"
DS_ID="$2"

DRIVER_PATH="${0%/*}"
UNI_PATH="${DRIVER_PATH}/../../datastore/storpool"
DS_NAME="one-ds-${DS_ID}"
MONITOR_HELPER="$UNI_PATH/monitor_helper"
SP_TEMPLATE_STATUS_JSON="/tmp/storpool_template_status.json"
SP_MONITOR_HELPER="cat $SP_TEMPLATE_STATUS_JSON"

if [ -f "${DRIVER_PATH}/../../addon-storpoolrc" ]; then
    . "${DRIVER_PATH}/../../addon-storpoolrc"
fi

declare ds_data
while read l; do
	ds_data=(${l//,/ })
done < <(storpool -j template list | jq -r ".data|map(select(.name==\"$DS_NAME\"))|.[]|[.replication,.placeAll,.placeTail,.iops,.bw]|@csv")

#splog "$PWD datastore $DS_ID (${ds_data[@]})>>>${DRV_ACTION:0:6}"

if [ "${DRV_ACTION:0:6}" = "system" ]; then
#	echo "$PWD/$0 $*" >/tmp/monitor_system.sh
	MONITOR_HELPER="${SP_MONITOR_HELPER:-$MONITOR_HELPER}"
	if [ -f "$SP_TEMPLATE_STATUS_JSON" ]; then
		:
	else
		echo "{[]}" >"$SP_TEMPLATE_STATUS_JSON"
		splog "$SP_TEMPLATE_STATUS_JSON not found. Created empty one."
	fi
	
	if [ ${#ds_data[@]} -eq 0  ]; then
#		splog "DATASTORE_ID $DS_ID not SP defined"
		exit 0
	fi
else
#	echo "$0 $*" >/tmp/monitor_image.sh
	SP_TEMPLATE_PROPAGATE="YES"
	[ -f "${0%/*}/../../addon-storpoolrc" ] && source "${0%/*}/../../addon-storpoolrc"
	
	XPATH="${UNI_PATH}/../xpath.rb -b $DRV_ACTION"
	unset i XPATH_ELEMENTS
	while IFS= read -r -d '' element; do
		XPATH_ELEMENTS[i++]="$element"
	done < <($XPATH \
		/DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
		/DS_DRIVER_ACTION_DATA/DATASTORE/ID \
		/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
		/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SP_REPLICATION \
		/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SP_PLACEALL \
		/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SP_PLACETAIL \
		/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SP_IOPS \
		/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SP_BW \
		/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SP_TEMPLATE_PROPAGATE \
		/DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/TM_MAD)
	
	unset i
	BASE_PATH="${XPATH_ELEMENTS[i++]}"
	DATASTORE_ID="${XPATH_ELEMENTS[i++]}"
	BRIDGE_LIST="${XPATH_ELEMENTS[i++]:-$HOSTNAME}"
	SP_REPLICATION="${XPATH_ELEMENTS[i++]:-2}"
	SP_PLACEALL="${XPATH_ELEMENTS[i++]}"
	SP_PLACETAIL="${XPATH_ELEMENTS[i++]:-$SP_PLACEALL}"
	SP_IOPS="${XPATH_ELEMENTS[i++]:--}"
	SP_BW="${XPATH_ELEMENTS[i++]:--}"
	SP_TEMPLATE_PROPAGATE="${XPATH_ELEMENTS[i++]:-$SP_TEMPLATE_PROPAGATE}"
	TM_MAD="${XPATH_ELEMENTS[i++]}"
	i=0
	if [ "$TM_MAD" = "storpool" ]; then
		cmd=
		DO_TEMPLATE=
		for e in SP_REPLICATION SP_PLACEALL SP_PLACETAIL SP_IOPS SP_BW; do
			eval new=\$$e
			current=${ds_data[$i]}
			current=${current//\"/}
			i=$((i+1))
			if [ "$new" = "$current" ]; then
				continue
			else
				key=${e#SP_}
				DO_TEMPLATE+="$key:$current "
				key=${key,,}
				case "$key" in
					bw)
						[ -n "${new//[[:digit:]]/}" ] || new+="K"
						;;
					placeall)
						key="placeAll"
						;;
					placetail)
						key="placeTail"
						;;
				esac
				cmd+="$key $new "
			fi
		done
		if [ -n "$cmd" ] ; then
			splog "template $DS_NAME $cmd(${DO_TEMPLATE%[[:space:]]})"
			storpool template "$DS_NAME" $cmd 2>&1 >/dev/null
			if [ "$SP_TEMPLATE_PROPAGATE" = "YES" ] && [ ${#ds_data[@]} -gt 0 ]; then
				splog "template $DS_NAME propagate"
				storpool template "$DS_NAME" propagate 2>&1 >/dev/null
			fi
#		else
#			splog "template $DS_NAME is OK"
		fi
	else
		splog "TM_MAD not StorPool ($TM_MAD)"
		exit 0
	fi
fi # DRV_ACTION

while IFS=',' read n t f; do
	if [ "${n//\"/}" = "$DS_NAME" ]; then
		u=$(( t - f ))
#		splog "$DS_NAME: u:$((u/1024/1024)) t:$((t/1024/1024)) f:$((f/1024/1024))"
		case "${DRV_ACTION:0:6}" in
			system)
				echo $((u/1024/1024)) $((t/1024/1024)) $((f/1024/1024))
				;;
			*)
				echo "USED_MB=$((u/1024/1024))"
				echo "TOTAL_MB=$((t/1024/1024))"
				echo "FREE_MB=$((f/1024/1024))"
				;;
		esac
		break
	fi
done < <($MONITOR_HELPER | jq -r '.data|map(select(.name))|.[]|[.name,.stored.capacity,.stored.free]|@csv')
