#!/bin/bash
#
# -------------------------------------------------------------------------- #
# Copyright 2016-2025, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

export PATH="/bin:/sbin:/usr/bin:/usr/sbin:${PATH}"

set -o pipefail

SP_JSON_PATH="/tmp"
SP_FE_JSON_PATH="/var/cache/addon-storpool-monitor"
ONE_HOME="${ONE_HOME:-/var/lib/one}"

SP_API_CALLS=(ClustersList VolumesSpace SnapshotsSpace VolumeTemplatesStatus)

ONE_VM_POOL_RUN="onevm list -x"
ONE_VM_POOL_XML="one.pool"

# Do sync to remote hosts
MONITOR_SYNC_REMOTE="YES"

ONEDATASTORE_XML="ds.xml"
# shellcheck source=tm/storpool/storpool_common.sh
source "${ONE_HOME}/remotes/tm/storpool/storpool_common.sh"

# load config
if [[ -f "${ONE_HOME}/remotes/addon-storpoolrc" ]]; then
    # shellcheck source=addon-storpoolrc
    source "${ONE_HOME}/remotes/addon-storpoolrc"
fi
if [[ -f "${ONE_HOME}/remotes/${0##*/}rc" ]]; then
    # shellcheck source=/dev/null
    source "${ONE_HOME}/remotes/${0##*/}rc"
fi

function doExpand()
{
    local _name="$1" _val=""
    eval "_val=\$${_name}"
    _val="${_val//_DATASTORE_ID_/${DS_ID}}"
    _val="${_val//_CLUSTER_ID_/${CLUSTER_ID}}"
    _val="${_val//_SP_API_HTTP_HOST_/${SP_API_HTTP_HOST}}"
    _val="${_val//_SP_JSON_PATH_/${SP_JSON_PATH}}"
    _val="${_val//_SP_FE_JSON_PATH_/${SP_FE_JSON_PATH}}"
    eval "${_name}=${_val}"
}

umask -S u=rwx,g=rwx,o= >/dev/null

ONE_PX="${ONE_PX:-one}"

if [[ -d "/opt/storpool/python3/bin" ]]; then
    export PATH="/opt/storpool/python3/bin:${PATH}"
fi

# locking...
lockFile="/var/lock/one/${0##*/}.lock"
if [[ -f "${lockFile}" ]]; then
    pid="$(<"${lockFile}")"
    mTime="$(stat -c %Y "${lockFile}")"
    if [[ -d "/proc/${pid}/" ]]; then
        cmdline="$(<"/proc/${pid}/cmdline")"
        if [[ "${cmdline/${0##*/}/}" == "${cmdline}" ]]; then
            splog "[I] Found ${lockFile} with PID ${pid}. Last modified ${mTime} (stale file)"
        else
            splog "[I] Found ${lockFile} with PID ${pid}. Last modified ${mTime} (still running)"
            exit 0
        fi
    else
        splog "[W] Can't find process info for PID ${pid}. Assuming stale lock ${lockFile}"
    fi
fi

# check that the oned process is running
if ! pgrep 'oned' >/dev/null; then
    if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
        splog "[D] There is no oned process running. Exit."
    fi
    exit 0
fi

# try detecting RAFT_LEADER_IP from opennebula's config
if [[ -z "${RAFT_LEADER_IP}" ]] && [[ -f "${ONE_HOME}/config" ]]; then
    #RAFT_LEADER_HOOK=ARGUMENTS=leader vlan11 10.163.1.250,COMMAND=raft/vip.sh
    RAFT_IP="$(awk '$0 ~ /^RAFT_LEADER_HOOK/{print $3}' "${ONE_HOME}/config" | tail -n 1)"
    if [[ -n "${RAFT_IP}" ]]; then
        RAFT_LEADER_IP="${RAFT_IP%%/*}"
        RAFT_LEADER_IP="${RAFT_LEADER_IP%%,*}"
    fi
fi

if [[ -n "${RAFT_LEADER_IP#*disabled}" ]]; then
    tmp="$(ip route get "${RAFT_LEADER_IP}" 2>/dev/null | head -n 1)"
    if [[ "${tmp:0:5}" == "local" ]]; then
        if boolTrue "DDEBUG_MONITOR_HELPER_SYNC"; then
            splog "[DD] Found leader IP (${RAFT_LEADER_IP})."
        fi
    else
        if boolTrue "DDEBUG_MONITOR_HELPER_SYNC"; then
            splog "[DD] There is no leader IP found (${RAFT_LEADER_IP}). Exit."
        fi
#        [[ -n ${SP_FE_JSON_PATH} ]] && rm -f "${SP_FE_JSON_PATH}/*json*"
        exit 0
    fi
fi

echo "$$" >"${lockFile}"
trapAdd "rm -f \"${lockFile}\""

# Global arrays ...
declare -a template_data_a
declare -A jFiles_a
declare -a to_delete_a

if [[ ! -d "${SP_FE_JSON_PATH}" ]]; then
    mkdir -p "${SP_FE_JSON_PATH}"
    splog "[I] Created ${SP_FE_JSON_PATH}"
fi

dsXML="${SP_FE_JSON_PATH}/${ONEDATASTORE_XML}"
# shellcheck disable=SC2086
onedatastore list ${ONE_ARGS} -x >"${dsXML}"
ret=$?
if [[ ${ret} -ne 0 ]]; then
    splog "[E] Error: Can't get datastore XML! $(head -n 1 "${dsXML}" || true) (ret:${ret})"
    exit "${ret}"
fi

_XPATH="${ONE_HOME}/remotes/datastore/xpath_multi.py"
declare -a _XPATH_A _XPATH_QUERY
_XPATH_A=(
    "${_XPATH}"
    "-s"
)
_XPATH_QUERY=(
    "/DATASTORE_POOL/DATASTORE/ID"
    "/DATASTORE_POOL/DATASTORE/STATE"
    "/DATASTORE_POOL/DATASTORE/CLUSTER_ID"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/TM_MAD"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_REPLICATION"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_PLACEALL"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_PLACETAIL"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_PLACEHEAD"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_IOPS"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_BW"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_API_HTTP_HOST"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_API_HTTP_PORT"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_AUTH_TOKEN"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_CLUSTER_ID"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_REMOTE_LOCATION"
    "/DATASTORE_POOL/DATASTORE/TEMPLATE/SP_SKIP_MONITOR"
)

unset i XPATH_ELEMENTS
while IFS='' read -r -u "${xpathfh}" element; do
	XPATH_ELEMENTS[i++]="${element}"
done {xpathfh}< <("${_XPATH_A[@]}" <"${SP_FE_JSON_PATH}/${ONEDATASTORE_XML}" "${_XPATH_QUERY[@]}" || true)
exec {xpathfh}<&-
unset i
_DS_ID="${XPATH_ELEMENTS[i++]}"
_DS_STATE="${XPATH_ELEMENTS[i++]}"
_DS_CLUSTER_ID="${XPATH_ELEMENTS[i++]}"
_DS_TM_MAD="${XPATH_ELEMENTS[i++]}"
_SP_REPLICATION="${XPATH_ELEMENTS[i++]}"
_SP_PLACEALL="${XPATH_ELEMENTS[i++]}"
_SP_PLACETAIL="${XPATH_ELEMENTS[i++]}"
_SP_PLACEHEAD="${XPATH_ELEMENTS[i++]}"
_SP_IOPS="${XPATH_ELEMENTS[i++]}"
_SP_BW="${XPATH_ELEMENTS[i++]}"
_SP_API_HTTP_HOST="${XPATH_ELEMENTS[i++]}"
_SP_API_HTTP_PORT="${XPATH_ELEMENTS[i++]}"
_SP_AUTH_TOKEN="${XPATH_ELEMENTS[i++]}"
_SP_CLUSTER_ID="${XPATH_ELEMENTS[i++]}"
_SP_REMOTE_LOCATION="${XPATH_ELEMENTS[i++]}"
_SP_SKIP_MONITOR="${XPATH_ELEMENTS[i++]}"

IFS=';' read -r -a DS_ID_ARRAY <<< "${_DS_ID}"
IFS=';' read -r -a DS_STATE_ARRAY <<< "${_DS_STATE}"
IFS=';' read -r -a DS_CLUSTER_ID_ARRAY <<< "${_DS_CLUSTER_ID}"
IFS=';' read -r -a DS_TM_MAD_ARRAY <<< "${_DS_TM_MAD}"
IFS=';' read -r -a SP_REPLICATION_ARRAY <<< "${_SP_REPLICATION}"
IFS=';' read -r -a SP_PLACEALL_ARRAY <<< "${_SP_PLACEALL}"
IFS=';' read -r -a SP_PLACETAIL_ARRAY <<< "${_SP_PLACETAIL}"
IFS=';' read -r -a SP_PLACEHEAD_ARRAY <<< "${_SP_PLACEHEAD}"
IFS=';' read -r -a SP_IOPS_ARRAY <<< "${_SP_IOPS}"
IFS=';' read -r -a SP_BW_ARRAY <<< "${_SP_BW}"
IFS=';' read -r -a SP_API_HTTP_HOST_ARRAY <<< "${_SP_API_HTTP_HOST}"
IFS=';' read -r -a SP_API_HTTP_PORT_ARRAY <<< "${_SP_API_HTTP_PORT}"
IFS=';' read -r -a SP_AUTH_TOKEN_ARRAY <<< "${_SP_AUTH_TOKEN}"
IFS=';' read -r -a SP_CLUSTER_ID_ARRAY <<< "${_SP_CLUSTER_ID}"
IFS=';' read -r -a SP_REMOTE_LOCATION_ARRAY <<< "${_SP_REMOTE_LOCATION}"
IFS=';' read -r -a SP_SKIP_MONITOR_ARRAY <<< "${_SP_SKIP_MONITOR}"

ts=$(date +%s)

if ! boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
    # shellcheck disable=SC2034
    DEBUG_SP_RUN_CMD=""
fi

for i in "${!DS_ID_ARRAY[@]}"; do
	[[ "${DS_TM_MAD_ARRAY[i]}" == "storpool" ]] || continue

	cmd=""
	DS_ID="${DS_ID_ARRAY[i]}"
    DS_CLUSTER_ID="${DS_CLUSTER_ID_ARRAY[i]}"
    SP_REMOTE_LOCATION="${SP_REMOTE_LOCATION_ARRAY[i]}"
	template_name="${ONE_PX}-ds-${DS_ID}"
	sp_token="${SP_AUTH_TOKEN_ARRAY[i]}"
	if [[ -n "${sp_token}" ]]; then
		export SP_AUTH_TOKEN="${sp_token}"
	else
		unset SP_AUTH_TOKEN
	fi
	sp_host="${SP_API_HTTP_HOST_ARRAY[i]}"
	if [[ -n "${sp_host}" ]]; then
		export SP_API_HTTP_HOST="${sp_host}"
	else
		unset SP_API_HTTP_HOST
	fi
	sp_port="${SP_API_HTTP_PORT_ARRAY[i]}"
	if [[ -n "${sp_port}" ]]; then
		export SP_API_HTTP_PORT="${sp_port}"
	else
		unset SP_API_HTTP_PORT
	fi
	export SP_PROPAGATE="${SP_TEMPLATE_PROPAGATE_ARRAY[i]:-${SP_TEMPLATE_PROPAGATE}}"
	if boolTrue "DEBUG_MOINTOR_HELPER_SYNC"; then
		if [[ -n "${SP_AUTH_TOKEN}${SP_API_HTTP_HOST}${SP_API_HTTP_PORT}" ]]; then
			splog "[D] API_TOKEN:${SP_AUTH_TOKEN:+DEFINED} API_HOST:${SP_API_HTTP_HOST} API_PORT:${SP_API_HTTP_PORT}"
		fi
	fi

	if boolTrue "SP_SKIP_MONITOR_ARRAY[i]"; then
		splog "DS_ID ${DS_ID} Skipped (SP_SKIP_MONITOR=${SP_SKIP_MONITOR_ARRAY[i]})"
		continue
	fi
    if [[ "${DS_STATE_ARRAY[i]}" != "0" ]]; then
	    if boolTrue "DEBUG_MOINTOR_HELPER_SYNC"; then
            splog "[D] Skipped Datastore ${DS_ID} STATE=${DS_STATE_ARRAY[i]}"
        fi
        continue
    fi

    spApiHttpHost="${SP_API_HTTP_HOST:-0.0.0.0}"

    # get the list of StorPool clusters (connected API)
#    declare -a sp_clusters
#    unset j
#    if storpoolRetry ClustersList; then
#        while IFS="," read -r -u 4 c_name; do
#            #apiClusterUid="${c_uid}"
#            sp_clusters[j++]="${c_name}"
#        done 4< <(jq -r '.data.clusters[]|.name' "${DATA_JSON}" || true)
#    fi

    # get the list of ONE clusters where the given datastore is a member

    _XPATH="${ONE_HOME}/remotes/datastore/xpath.rb"
    _XPATH_A=(
        "${_XPATH}"
        "--stdin"
    )
    _XPATH_QUERY=(
        "%m%/DATASTORE_POOL/DATASTORE[ID=${DS_ID}]/CLUSTERS/ID"
    )
    while IFS='' read -r -u "${xpathfh}" -d '' _element; do
        # shellcheck disable=SC2206
        CLUSTER_ID_ARRAY+=(${_element})
    done {xpathfh}< <("${_XPATH_A[@]}" <"${SP_FE_JSON_PATH}/${ONEDATASTORE_XML}" "${_XPATH_QUERY[@]}" || true)

	if [[ -n "${DDEBUG_MOINTOR_HELPER_SYNC}" ]]; then
		splog "[DD] DS_ID=${DS_ID} ${SP_FE_JSON_PATH}/${ONEDATASTORE_XML} CLUSTER_ID_ARRAY:${CLUSTER_ID_ARRAY[*]}"
	fi


    # walk the API calls
    for apicall in "${SP_API_CALLS[@]}"; do
        #splog ">>>API::${apicall}<<< "
        skipCall=0
        jsonFile="${SP_FE_JSON_PATH}/json-${apicall}-${spApiHttpHost}"
        doExpand "jsonFile"
        tempJson="${TMPDIR}/json-${apicall}-${spApiHttpHost}"
        if [[ -f ${jsonFile} ]] && [[ -r ${jsonFile} ]]; then
            tmp="SP_${apicall^^}_SECONDS"
            if [[ -n ${!tmp} ]]; then
                cSeconds="${!tmp}"
            else
                cSeconds="${SP_DEFAULT_SECONDS:-1800}"
            fi
            if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
                splog "[${apicall}] caching seconds ${cSeconds} (${tmp})"
            fi
            mTime="$(stat --format "%Y" "${jsonFile}")"
            if [[ $((mTime + cSeconds)) -gt ${ts} ]]; then
                if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
                    splog "[${apicall}] skipped ${jsonFile} ${ts} < ($((mTime+cSeconds))) ${mTime} + ${cSeconds}"
                fi
                skipCall=1
            fi
        fi
        if [[ ${skipCall} -eq 0 ]]; then
            if [[ ! -f ${tempJson} ]]; then
                if DO_MULTICLUSTER=1 DO_ALLCLUSTERS=1 storpoolRetry "${apicall}"; then
                    cp "${DATA_JSON}" "${tempJson}"
                    ret=$?
                    if boolTrue "DEBUG_MONITOR_HELPER_SYNC" || [[ ${ret} -ne 0 ]]; then
                        splog "cp ${DATA_JSON} ${tempJson} (${ret})"
                    fi
                else
                    splog "[${apicall}] Warning: Can't get API data."
                fi
            else
                if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
                    splog "Using the existing file ${tempJson}"
                fi
            fi
            cp "${tempJson}" "${jsonFile}"
            ret=$?
            if [[ ${ret} -ne 0 ]]; then
                splog "Can't copy ${tempJson} to ${jsonFile} (${ret}). Next"
                continue
            fi
            # split the json file per StorPool cluster
            ret=-1
            while read -r -u 4 clusterId; do
                jq -r -c --arg clusterId "${clusterId}" '.data.clusters[]|select(.clusterId==$clusterId)|.response' "${jsonFile}" > "${jsonFile}-${clusterId}"
                ret=$?
                if [[ ${ret} -ne 0 ]]; then
                    splog "Can't process ${jsonFile} for ${clusterId} (${ret})"
                fi
            done 4< <(jq -r '.data.clusters[]|.clusterId' "${jsonFile}" || true)
            if [[ ${ret} -eq -1 ]]; then
                splog "No clusters found in ${jsonFile}. Next"
                continue
            fi
        fi
        if [[ ! -f "${jsonFile}" ]]; then
            splog "Missing ${jsonFile}. Next"
            continue
        fi
        jFiles_a[${jsonFile}]="${jsonFile##*/}"
        # create a symlink jsonPath/jsonfile -> jsonpath/$cluster_id/json-${apicall}-${DS_ID}
        for ONECLUSTER_ID in "${CLUSTER_ID_ARRAY[@]}"; do
            SP_MONITOR_CACHE_CLUSTER="${SP_FE_JSON_PATH}/${ONECLUSTER_ID}"
            if [[ ! -d "${SP_MONITOR_CACHE_CLUSTER}" ]]; then
                mkdir -p "${SP_MONITOR_CACHE_CLUSTER}"
                splog "($?) mkdir ${SP_MONITOR_CACHE_CLUSTER}"
            fi
            SP_MONITOR_CACHE_CLUSTER+="/json-${apicall}-${DS_ID}"
            ln -sf "${jsonFile}" "${SP_MONITOR_CACHE_CLUSTER}"
            ret=$?
            if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
                splog "[${apicall}] DS_ID:${DS_ID} ONECLUSTER_ID:${ONECLUSTER_ID} ${SP_MONITOR_CACHE_CLUSTER} (${ret})"
            fi
        done
    done
    if [[ -n ${ONE_VM_POOL_RUN} ]]; then
        tmpFile="${TMPDIR}/vm.pool"
        if [[ ! -f "${tmpFile}" ]]; then
            eval "${ONE_VM_POOL_RUN}" 2>/dev/null >"${tmpFile}"
            ret=$?
            if boolTrue "DEBUG_MONITOR_HELPER_SYNC" || [[ ${ret} -ne 0 ]]; then
                splog "eval ${ONE_VM_POOL_RUN} > ${tmpFile} (${ret})"
                if [[ ${ret} -ne 0 ]]; then
                    continue
                fi
            fi
        fi
        rFile="${SP_FE_JSON_PATH}/${ONE_VM_POOL_XML##*/}"
        doExpand "rFile"
        ${CP:-cp} "${tmpFile}" "${rFile}"
        ret=$?
        if [[ ${ret} -ne 0 ]]; then
            splog "Can't copy ${tmpFile} to ${rFile} (${ret})"
            continue
        fi
    fi
    # create/update ONE datastore attributes
    tmpFile="${TMPDIR}/${DS_ID}.update"
    # shellcheck disable=SC2034
    {
        replication="${SP_REPLICATION_ARRAY[i]}"
        placeAll="${SP_PLACEALL_ARRAY[i]}"
        placeTail="${SP_PLACETAIL_ARRAY[i]}"
        placeHead="${SP_PLACEHEAD_ARRAY[i]}"
        iops="${SP_IOPS_ARRAY[i]}"
        bw="${SP_BW_ARRAY[i]}"
        clusterId="${SP_CLUSTER_ID_ARRAY[i]}"
    }
    jsonFile="${SP_FE_JSON_PATH}/json-VolumeTemplatesStatus-${spApiHttpHost}"
    #DO_REMOTE="~${SP_REMOTE_LOCATION}" storpoolRetry VolumeTemplatesList
    tmp="$(jq -r --arg clusterId "${SP_REMOTE_LOCATION:-}" --arg tName "${template_name}" '.data.clusters[]|select(.clusterId==$clusterId).response.data[]|select(.name==$tName)|(.replication|tostring)+","+.placeAll+","+.placeTail+","+.placeHead+","+(.iops|tostring)+","+(.bw|tostring)' "${jsonFile}")"
    ret=$?
    if [[ -z "${tmp}" ]]; then
        splog "[W] Missing StorPool template '${template_name}' for datastore ${DS_ID} SP_REMOTE_LOCATION=${SP_REMOTE_LOCATION} file:${jsonFile} (${ret})"
        to_delete_a+=("${jsonFile}")
    fi
    declare -a template_data_a
    declare -a template_names_a
    IFS=',' read -r -a template_data_a <<< "${tmp}"
    template_names_a=(replication placeAll placeTail placeHead iops bw)
    for entry in ${!template_names_a[*]}; do
        name="${template_names_a[entry]}"
        data="${template_data_a[entry]}"
        if [[ -n ${data} ]]; then
            if [[ ${data} != "${!name}" ]]; then
                echo "SP_${name^^}=${data}" >>"${tmpFile}"
                splog "[I] DS_ID ${DS_ID} update SP_${name^^}=${data} //old:'${!name}'"
            fi
        fi
    done
    if [[ ${clusterId} != "${SP_REMOTE_LOCATION}" ]]; then
        echo "SP_CLUSTER_ID=${SP_REMOTE_LOCATION}" >>"${tmpFile}"
        splog "[I] DS_ID ${DS_ID} update SP_CLUSTER_ID=${SP_REMOTE_LOCATION} //old:'${clusterId}'"
    fi
    if [[ -s ${tmpFile} ]]; then
        # shellcheck disable=SC2086
        onedatastore update ${ONE_ARGS} "${DS_ID}" --append "${tmpFile}" 2>&1 | tee "${TMPDIR}/errfile"
        ret=$?
        splog "[I] (${ret}) onedatastore update ${ONE_ARGS} ${DS_ID} --append ${tmpFile}"
        if [[ ${ret} -ne 0 ]]; then
            cp "${tmpFile}" "/tmp/update-ds-${DS_ID}-${ret}.template"
            while read -r -u 4 errline; do
                splog "[E] ${errline}"
            done 4< <(cat "${TMPDIR}/errfile" || true)
        fi
    fi
    if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
        splog "[D] DS_ID:${DS_ID} jFiles_a:${jFiles_a[*]}"
    fi
done

# hosts syncing

if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
    splog "[D] Hosts processing ..."
fi
tmpXML="${TMPDIR}/onehost.list"

onehost list -x >"${tmpXML}"
ret=$?
if [[ ${ret} -ne 0 ]]; then
    splog "[E] (oneHostList) Error: Can't get info! $(head -n1 "${tmpXML}" || true) (ret:${ret})"
    exit "${ret}"
fi

_XPATH="${ONE_HOME}/remotes/datastore/xpath_multi.py"
_XPATH_A=(
    "${_XPATH}"
    "-s"
)
_XPATH_QUERY=(
    "/HOST_POOL/HOST/ID"
    "/HOST_POOL/HOST/NAME"
    "/HOST_POOL/HOST/STATE"
    "/HOST_POOL/HOST/CLUSTER_ID"
    "/HOST_POOL/HOST/TEMPLATE/SP_CLUSTER_ID"
    "/HOST_POOL/HOST/SP_JSON_PATH"
)
unset i XPATH_ELEMENTS
while IFS='' read -r -u "${xpathfh}" element; do
	XPATH_ELEMENTS[i++]="${element}"
done {xpathfh}< <("${_XPATH_A[@]}" <"${tmpXML}" "${_XPATH_QUERY[@]}" || true)
exec {xpathfh}<&-
rm -f "${tmpXML}"
unset i
_HOST_ID="${XPATH_ELEMENTS[i++]}"
_HOST_NAME="${XPATH_ELEMENTS[i++]}"
_HOST_STATE="${XPATH_ELEMENTS[i++]}"
_HOST_ONECLUSTER_ID="${XPATH_ELEMENTS[i++]}"
_HOST_SP_CLUSTER_ID="${XPATH_ELEMENTS[i++]}"
_HOST_SP_JSON_PATH="${XPATH_ELEMENTS[i++]}"

if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
    splog "[D] ${_HOST_ID}|${_HOST_NAME}|${_HOST_ONECLUSTER_ID}|${_HOST_SP_CLUSTER_ID}|${_HOST_STATE}"
fi

IFS=';' read -r -a HOST_ID_ARRAY <<< "${_HOST_ID}"
IFS=';' read -r -a HOST_NAME_ARRAY <<< "${_HOST_NAME}"
IFS=';' read -r -a HOST_STATE_ARRAY <<< "${_HOST_STATE}"
IFS=';' read -r -a HOST_ONECLUSTER_ID_ARRAY <<< "${_HOST_ONECLUSTER_ID}"
IFS=';' read -r -a HOST_SP_CLUSTER_ID_ARRAY <<< "${_HOST_SP_CLUSTER_ID}"
IFS=';' read -r -a HOST_SP_JSON_PATH_ARRAY <<< "${_HOST_SP_JSON_PATH}"

_lHost="$(hostname -s)"
for i in "${!HOST_ID_ARRAY[@]}"; do
    if [[ -z "${HOST_ID_ARRAY[i]}" ]]; then
        if boolTrue "DDEBUG_MONITOR_HELPER_SYNC"; then
            splog "[D] Skip empty host ID ${i}:${HOST_ID_ARRAY[i]}"
        fi
        continue
    fi
    _rHost="${HOST_NAME_ARRAY[i]}"
    _cluster_id="${HOST_ONECLUSTER_ID_ARRAY[i]}"
    _sp_cluster_id="${HOST_SP_CLUSTER_ID_ARRAY[i]}"
    _destDir="${HOST_SP_JSON_PATH_ARRAY[i]:-${SP_JSON_PATH}}"
    _state="${HOST_STATE_ARRAY[i]}"
    if [[ -z "${_state}" ]] || [[ ${_state} -ge 4 ]]; then
        if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
            splog "[D] Skip host ${_rHost} state:${_state}"
        fi
        continue
    fi

    while read -r -u "${ffh}" _jFile; do
        sFile="$(realpath "${_jFile}" || true)"
        dFile="${sFile##*/}"
        IFS='-' read -r -a dFileArr <<< "${dFile}"
        dFile="${dFileArr[0]}-${dFileArr[1]}"
        if [[ "${_rHost}" == "${_lHost}" ]]; then
            if [[ ! -d ${_destDir} ]]; then
                mkdir -p "${_destDir}"
                cp -L "${sFile}" "${_destDir}/${dFile}"
                ret=$?
                if [[ ${ret} -ne 0 ]]; then
                    splog "[I] ${_rHost} (localhost) copy ${sFile} to ${_destDir}/${dFile} returned ${ret}"
                else
                    if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
                        splog "[D] ${_rHost} (localhost) ${sFile} copied to ${_destDir}/${dFile} (cluster_id:${_cluster_id})"
                    fi
                fi
            fi
        elif boolTrue "MONITOR_SYNC_REMOTE" "${MONITOR_SYNC_REMOTE}"; then # make shellcheck happy
            ssh -o ConnectTimeout="${sshConnectTimeout:-3}" \
                -o ConnectionAttempts="${sshConnectionAttempts:-3}" \
                "${_rHost}" "[[ -d \"${_destDir}\" ]] || mkdir -p \"${_destDir}\" && cat >\"${_destDir}/${dFile}\"" < "${sFile}" 2>/dev/null >/dev/null
            ret=$?
            if [[ ${ret} -ne 0 ]]; then
                splog "[I] Copy ${sFile} to ${_rHost}:${_destDir}/${dFile} returned ${ret}"
            else
                if boolTrue "DEBUG_MONITOR_HELPER_SYNC"; then
                    splog "[D ]Copy ${sFile} copied to ${_rHost}:${_destDir}/${dFile} (cluster_id:${_cluster_id})"
                fi
            fi
        fi
    done {ffh}< <(find "${SP_FE_JSON_PATH}" -type f -name "*-${_sp_cluster_id}" || true)
done

rm -f "${lockFile}"

if boolTrue "DEBUG_MOINTOR_HELPER_SYNC"; then
	splog "[D] END"
fi
