#!/bin/bash
#

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

function splog() { logger -t "ds_sp_${0##*/}" "[$$] $*"; }

if [[ -n "$2" ]]; then
    DRV_ACTION="$1"
    DS_ID="$2"
else
    DRV_ACTION="$(cat)"
    DS_ID="$1"
fi

export DRV_ACTION

DRIVER_PATH="$(dirname "$0")"
SP_JSON_PATH="/tmp"
SP_FE_JSON_PATH="/var/cache/addon-storpool-monitor"
SP_TEMPLATE_STATUS_JSON="json-VolumeTemplatesStatus"
SP_TEMPLATE_STATUS_PATH="_SP_FE_JSON_PATH_/_SP_TEMPLATE_STATUS_JSON_-_SP_API_HTTP_HOST_-_SP_CLUSTER_ID_"
# alternate calculation of the Free space
ALT_STATS=""

export LOG_PREFIX="ds"

if [[ -f "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh" ]]; then
    # shellcheck source=tm/storpool/storpool_common.sh
	source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"
else
	splog "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh not found!"
    exit 1
fi

DS_NAME="${ONE_PX}-ds-${DS_ID}"

if boolTrue "DEBUG_DS_MONITOR"; then
	splog "[D] ${PWD} datastore ${DS_ID} '${DRV_ACTION:0:6}'"
fi

if [[ ${DRV_ACTION:0:6} == "system" ]]; then
	SP_TEMPLATE_STATUS_PATH="${SP_CMD_TEMPLATE_STATUS_SYSTEM:-${SP_TEMPLATE_STATUS_PATH}}"
	if [[ ! -f "${SP_TEMPLATE_STATUS_PATH}/${SP_TEMPLATE_STATUS_JSON}" ]]; then
		echo "{[]}" >"${SP_TEMPLATE_STATUS_PATH}/${SP_TEMPLATE_STATUS_JSON}"
		splog "${SP_TEMPLATE_STATUS_PATH}/${SP_TEMPLATE_STATUS_JSON} not found. Created an empty one."
	fi
#	echo "bash -x ${PWD}/$0 $*" >"/tmp/monitor_system.sh"
else
	SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH_IMAGE:-${SP_TEMPLATE_STATUS_PATH}}"
	oneDsDriverAction
	if [[ -n "${CLUSTERS_ID}" ]]; then
		read -r -a CLUSTERS_ID_ARRAY <<< "${CLUSTERS_ID}"
		CLUSTER_ID="${CLUSTERS_ID_ARRAY[0]}"
	fi
#	echo "bash -x $0 $*" >"/tmp/monitor-${DS_ID}-${CLUSTER_ID}.sh"
fi # DRV_ACTION


# expand the template variables
SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH//_SP_TEMPLATE_STATUS_JSON_/${SP_TEMPLATE_STATUS_JSON}}"
SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH//_DATASTORE_ID_/${DS_ID}}"
SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH//_SP_CLUSTER_ID_/${SP_CLUSTER_ID}}"
SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH//_CLUSTER_ID_/${CLUSTER_ID}}"
SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH//_SP_API_HTTP_HOST_/${SP_API_HTTP_HOST:-0.0.0.0}}"
SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH//_SP_JSON_PATH_/${SP_JSON_PATH}}"
SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH//_SP_FE_JSON_PATH_/${SP_FE_JSON_PATH}}"
SP_TEMPLATE_STATUS_PATH="${SP_TEMPLATE_STATUS_PATH//_SP_TEMPLATE_STATUS_JSON_/${SP_TEMPLATE_STATUS_JSON}}"

if boolTrue "DDEBUG_DS_MONITOR"; then
	splog "DS_ID=${DS_ID} ${SP_CLUSTER_ID} SP_TEMPLATE_STATUS_PATH:${SP_TEMPLATE_STATUS_PATH} ${SP_TEMPLATE_STATUS_JSON}"
fi

JSON_FILE="${SP_FE_JSON_PATH}/${SP_TEMPLATE_STATUS_JSON}-${SP_API_HTTP_HOST:-0.0.0.0}-${SP_CLUSTER_ID}"

while read -r -u "${jqfh}" name storedCapacity storedFree u2 u3; do
	if [[ "${name}" == "${DS_NAME}" ]]; then
		if boolTrue "ALT_STATS" "${ALT_STATS}"; then # make shellcheck happy
			storedFree=$(( storedFree + u2 + u3 ))
		fi
		used=$(( storedCapacity - storedFree ))
		case "${DRV_ACTION:0:6}" in
			system)
				echo $((used/1024/1024)) $((storedCapacity/1024/1024)) $((storedFree/1024/1024))
				DS_TYPE="SYSTEM_DS"
				;;
			*)
				echo "USED_MB=$((used/1024/1024))"
				echo "TOTAL_MB=$((storedCapacity/1024/1024))"
				echo "FREE_MB=$((storedFree/1024/1024))"
				;;
		esac
		if boolTrue "DEBUG_DS_MONITOR"; then
			splog "[D] ${DS_TYPE} ${DS_ID} SP_CLUSTER_ID:${SP_CLUSTER_ID} used:$((used/1024/1024)) storedCapacity:$((storedCapacity/1024/1024)) storedFree:$((storedFree/1024/1024)) u2:$((u2/1024**2)) u3:$((u3/1024**2))"
		fi
		break
	fi
done {jqfh}< <( jq -r '.data[]|.name+" "+(.stored.capacity|tostring)+" "+(.stored.free|tostring)+" "+(.stored.internal.u2|tostring)+" "+(.stored.internal.u3|tostring)' "${JSON_FILE}" || true)
