#!/bin/bash
#

# -------------------------------------------------------------------------- #
# Copyright 2015-2016, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

function splog() { logger -t "ds_sp_${0##*/}" "$*"; }

DRV_ACTION="$1"
DS_ID="$2"

DRIVER_PATH="${0%/*}"
UNI_PATH="${DRIVER_PATH}/../../datastore/storpool"
MONITOR_HELPER="$UNI_PATH/monitor_helper"
SP_TEMPLATE_STATUS_JSON="/tmp/storpool_template_status.json"
SP_MONITOR_HELPER="cat $SP_TEMPLATE_STATUS_JSON"
SP_MONITOR_UPDATE_TEMPLATE=
DS_NAME="one-ds-$DS_ID"

if [ -f "${DRIVER_PATH}/../../addon-storpoolrc" ]; then
    source "${DRIVER_PATH}/../../addon-storpoolrc"
fi
if [ -f "/etc/storpool/addon-storpool.conf" ]; then
    source "/etc/storpool/addon-storpool.conf"
fi

if [ -n "$DEBUG_DATASTORE_MONITOR" ]; then
	splog "$PWD datastore $DS_ID ${DRV_ACTION:0:6}"
fi

if [ "${DRV_ACTION:0:6}" = "system" ]; then
#	echo "$PWD/$0 $*" >/tmp/monitor_system.sh
	MONITOR_HELPER="${SP_MONITOR_HELPER:-$MONITOR_HELPER}"
	if [ -f "$SP_TEMPLATE_STATUS_JSON" ]; then
		:
	else
		echo "{[]}" >"$SP_TEMPLATE_STATUS_JSON"
		splog "$SP_TEMPLATE_STATUS_JSON not found. Created empty one."
	fi
#else
#	echo "$0 $*" >/tmp/monitor_image.sh
fi # DRV_ACTION

while IFS=',' read n t f; do
	if [ "${n//\"/}" = "$DS_NAME" ]; then
		u=$(( t - f ))
#		splog "$DS_NAME: u:$((u/1024/1024)) t:$((t/1024/1024)) f:$((f/1024/1024))"
		case "${DRV_ACTION:0:6}" in
			system)
				echo $((u/1024/1024)) $((t/1024/1024)) $((f/1024/1024))
				;;
			*)
				echo "USED_MB=$((u/1024/1024))"
				echo "TOTAL_MB=$((t/1024/1024))"
				echo "FREE_MB=$((f/1024/1024))"
				;;
		esac
		break
	fi
done < <($MONITOR_HELPER | jq -r '.data|map(select(.name))|.[]|[.name,.stored.capacity,.stored.free]|@csv')
