#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# rm base64drvActionXML id
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Set up the environment to source common tools
#-------------------------------------------------------------------------------

if [[ -n "${ONE_LOCATION}" ]]; then
    LIB_LOCATION="${ONE_LOCATION}/lib"
else
    LIB_LOCATION="/usr/lib/one"
fi
# shellcheck source=/dev/null
source "${LIB_LOCATION}/sh/scripts_common.sh"

DRIVER_PATH="$(dirname "$0")"
# shellcheck source=/dev/null
source "${DRIVER_PATH}/../libfs.sh"

export LOG_PREFIX="ds"

# shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"

#-------------------------------------------------------------------------------
# Get rm and datastore arguments from OpenNebula core
#-------------------------------------------------------------------------------

if [[ -n "$2" ]]; then
    DRV_ACTION="$1"
    ID="$2"
else
    DRV_ACTION="$(cat)"
    ID="$1"
fi

oneDsDriverAction

#-------------------------------------------------------------------------------
# Remove Image from Datastore
#-------------------------------------------------------------------------------
SP_VOL="${ONE_PX}-img-${ID}"
VOL_UID=$(kvGet byName "${SP_VOL}")
STORPOOL_EXIST_HINT="Snapshot Volume"
if [[ -n "${VOL_UID}" ]]; then
    storpoolDelete "${VOL_UID}" "force" "snaps" "${REMOTE_BACKUP_DELETE}" "\"img\":\"${SP_VOL}\",\"reason\":\"datastore_delete\""
    if boolTrue "VMSNAPSHOT_DELETE_ON_TERMINATE"; then
        storpoolSnapshotsDelete "${SP_VOL}" "${VMSNAPSHOT_TAG}"
    fi
else
    splog "No globalId for ${SP_VOL} (byName)"
fi
# Remove the temp volume in case of stale broken import
SP_TEMP_VOL="${SP_VOL}-$(echo "${SP_VOL}" | md5sum | awk '{print $1}')"
TEMP_VOL_UID=$(kvGet byName "${SP_TEMP_VOL}")
if [[ -n "${TEMP_VOL_UID}" ]]; then
    storpoolDelete "${TEMP_VOL_UID}" "force" "" "" "\"img\":\"${SP_TEMP_VOL}\",\"reason\":\"datastore_delete\""
fi

splog "END ${VOL_UID} (${SP_VOL})"
exit 0
