#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015, StorPool (storpool.com)                                    #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# snap_revert base64drvActionXML id
#-------------------------------------------------------------------------------

function splog() { logger -t "ds_sp_${0##*/}" "$*"; }

#-------------------------------------------------------------------------------
# Set up the environment to source common tools
#-------------------------------------------------------------------------------

if [ -n "${ONE_LOCATION}" ]; then
    LIB_LOCATION=$ONE_LOCATION/lib
else
    LIB_LOCATION=/usr/lib/one
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh

#-------------------------------------------------------------------------------
# Get stat and datastore arguments from OpenNebula core
#-------------------------------------------------------------------------------

DRV_ACTION=$1
ID=$2

if type base64 2>&1 >/dev/null; then
    echo $DRV_ACTION | base64 -d >"/tmp/ds_sp_${0##*/}-$ID"
fi

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH /DS_DRIVER_ACTION_DATA/IMAGE/SOURCE \
                /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
                /DS_DRIVER_ACTION_DATA/IMAGE/TARGET_SNAPSHOT)

unset i
SOURCE="${XPATH_ELEMENTS[i++]}"
BRIDGE_LIST="${XPATH_ELEMENTS[i++]}"
TARGET_SNAPSHOT="${XPATH_ELEMENTS[i++]}"

DST_HOST=`get_destination_host $ID`

splog "\
${ID:+ID=$ID }\
${SOURCE:+SOURCE=$SOURCE }\
${DST_HOST:+DST_HOST=$DST_HOST }\
${TARGET_SNAPSHOT:+TARGET_SNAPSHOT=$TARGET_SNAPSHOT }\
"
if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

SP_VOL="${SOURCE##*/}"
SP_SNAP="${SP_VOL}-snap$TARGET_SNAPSHOT"

SP_TMPVOL="${SP_VOL}-$(date +%s)$(mktemp --dry-tun XXXXXX)"

SNAP_REVERT_CMD=$(cat <<EOF
    set -e
    export PATH=/bin:/sbin:/usr/bin:/usr/sbin:\$PATH
    splog(){ logger -t ds_sp_${0##*/} "\$*"; }

    splog "volume $SP_VOL rename ${SP_TMPVOL}"
    storpool volume "$SP_VOL" rename "${SP_TMPVOL}"

    trap 'splog "(\$?) revert $SP_TMPVOL to $SP_VOL"; storpool volume "$SP_TMPVOL" rename "$SP_VOL";' EXIT TERM INT HUP

    splog "volume $SP_VOL parent $SP_SNAP"
    storpool volume "$SP_VOL" parent "$SP_SNAP"

    trap - EXIT TERM INT HUP

    splog "volume $SP_TMPVOL delete"
    storpool volume "$SP_TMPVOL" delete "$SP_TMPVOL"

    splog "END SNAP_REVERT_CMD"
EOF
)

ssh_exec_and_log "$DST_HOST" "$SNAP_REVERT_CMD" \
                 "Error reverting snapshot $SP_SNAP"

splog "END"
