#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2024, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# snap_revert base64drvActionXML id
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Set up the environment to source common tools
#-------------------------------------------------------------------------------

if [[ -n "${ONE_LOCATION}" ]]; then
    LIB_LOCATION="${ONE_LOCATION}/lib"
else
    LIB_LOCATION="/usr/lib/one"
fi

# shellcheck source=/dev/null
. "${LIB_LOCATION}/sh/scripts_common.sh"

DRIVER_PATH="$(dirname "$0")"
# shellcheck source=/dev/null
source "${DRIVER_PATH}/../libfs.sh"

export LOG_PREFIX="ds"

# shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"

#-------------------------------------------------------------------------------
# Get stat and datastore arguments from OpenNebula core
#-------------------------------------------------------------------------------

if [[ -n "$2" ]]; then
    DRV_ACTION="$1"
    ID="$2"
else
    DRV_ACTION="$(cat)"
    ID="$1"
fi

oneDsDriverAction

SP_VOL="${SOURCE##*/}"
SP_SNAP="${SP_VOL}-snap${TARGET_SNAPSHOT}"
SP_TMPVOL="${SP_VOL}-$(date +%s || true)-$(mktemp --dry-run XXXXXX || true)"
SP_TEMPLATE="${ONE_PX:-one}-ds-${DATASTORE_ID}"

export SP_TMPVOL SP_TEMPLATE  # TBD: remove

storpoolSnapshotRevert "${SP_SNAP}" "${SP_VOL}"

SP_QOSCLASS="${IMAGE_SP_QOSCLASS:-${DS_SP_QOSCLASS:-${DEFAULT_QOSCLASS}}}"
debug_sp_qosclass

storpoolVolumeTag "${SP_VOL}" "one;${LOC_TAG_VAL};${SP_QOSCLASS}" "virt;${LOC_TAG:-nloc};qc"

splog "END"
