#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# stat base64drvActionXML id
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Set up the environment to source common tools
#-------------------------------------------------------------------------------

if [[ -n "${ONE_LOCATION}" ]]; then
    LIB_LOCATION="${ONE_LOCATION}/lib"
else
    LIB_LOCATION="/usr/lib/one"
fi
# shellcheck source=/dev/null
source "${LIB_LOCATION}/sh/scripts_common.sh"

DRIVER_PATH="$(dirname "$0")"

# shellcheck source=/dev/null
source "${DRIVER_PATH}/../libfs.sh"

export LOG_PREFIX="ds"

# shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"

#-------------------------------------------------------------------------------
# Get stat and datastore arguments from OpenNebula core
#-------------------------------------------------------------------------------

if [[ -n "$2" ]]; then
    DRV_ACTION="$1"
    ID="$2"
else
    DRV_ACTION="$(cat)"
    ID="$1"
fi

oneDsDriverAction

SIZE=0

#-------------------------------------------------------------------------------
# Test file
#-------------------------------------------------------------------------------
[[ -r "${IMAGE_PATH}" ]] || splog "[W] Not readable file: ${IMAGE_PATH}"
[[ -w "${IMAGE_PATH}" ]] || splog "[W] Not writable file: ${IMAGE_PATH}"
[[ -s "${IMAGE_PATH}" ]] || splog "[W] Zero size file: ${IMAGE_PATH}"
[[ ! -L "${IMAGE_PATH}" ]] || splog "[W] Is symlink: ${IMAGE_PATH}"
[[ ! -b "${IMAGE_PATH}" ]] || splog "[W] Is block device: ${IMAGE_PATH}"

#-------------------------------------------------------------------------------
# Compute the size
#-------------------------------------------------------------------------------

case "${IMAGE_PATH,,}" in
    *vmdk|*vhdx)
        qemu_img_info "${IMAGE_PATH}" || true
        if [[ -n "${QEMU_IMG_VIRTUAL_SIZE}" ]] && [[ ${QEMU_IMG_VIRTUAL_SIZE} -gt 0 ]]; then
            # round up to 1MiB
            SIZE=$(((QEMU_IMG_VIRTUAL_SIZE+1048575)/1048576))
        else
            SIZE=0
        fi
        ;;
    *)
        SIZE="$(fs_size "${IMAGE_PATH}")"
        RET=$?
        if [[ ${RET} -ne 0 ]]; then
            SIZE=0
        fi
        ;;
esac

if [[ ${SIZE} -eq 0 ]]; then
    oneSnapshotLookup "${IMAGE_PATH##*/}"
    if [[ -n ${SNAPSHOT_NAME} ]]; then
        if kvGetUid "${SNAPSHOT_NAME}"; then
            ENTRY="${SP_UID}"
        else
            ENTRY="${SNAPSHOT_NAME}"
        fi
        if ! storpoolSnapshotInfo "${ENTRY}"; then
            msg="Can't get StorPool Snapshot data for '${ENTRY}' ($?)"
            splog "[E] ${msg}"
            log "${msg}"
            exit 254
        fi
        if [[ ${ENTRY:0:1} == "~" ]]; then
            SP_UID="${ENTRY}"
        else
            SP_UID="~${X_GLOBALID}"
        fi
        SIZE="${X_SIZE}"
        SIZE=$((SIZE/1024**2))
        splog "[I] ${SP_UID} (${SNAPSHOT_NAME}) SIZE:${SIZE} cluster ${X_CLUSTERID}"
    fi
fi

if [[ -z "${SIZE}" ]] || [[ "${SIZE}" == "0" ]]; then
    _msg="Cannot determine size for ${IMAGE_PATH}"
    log_error "${_msg}"
    splog "[E] ${_msg}"
    exit 255
fi

splog "END SIZE='${SIZE}'"
echo "${SIZE}"
