#!/bin/bash
#
# -------------------------------------------------------------------------- #
# Copyright 2015-2019, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
#

# configure in /etc/one/oned.conf
#
#VM_HOOK = [
#    name      = "net_fw_hook",
#    on        = "CUSTOM",
#    state     = "ACTIVE",
#    lcm_state = "HOTPLUG_NIC",
#    command   = "net_fw_hook",
#    remote    = "YES",
#    arguments = "-i $TEMPLATE" ]
#

#DEBUG=1

me=${0##*/}
CWD="$(dirname "$0")"

tmpb64="$(mktemp -t net_hook_XXXXXX)"
trap 'rm -f "$tmpb64"' EXIT QUIT TERM HUP
if [ ! -t 0 ]; then
    cat > "$tmpb64"
fi
if [ ! -s "$tmpxml" ]; then
    echo "$1" > "$tmpb64"
fi

XPATH="$CWD/../datastore/xpath.rb"
ts="$(date +%s)"

if [ -n "$DEBUG" ]; then
    base64 -d "$tmpb64" | xmllint --format - >"/tmp/${me}-${ts}.xml"
    sudo ipset save >"/tmp/${me}-${ts}.ipset"
fi

ALIAS_XPATH="/VM/TEMPLATE/NIC_ALIAS[ATTACH=\"YES\"]"
unset i XE
while IFS= read -r -d '' element;do
    XE[i++]="$element"
done < <(base64 -d "$tmpb64" | $XPATH --stdin \
   /VM/ID \
   $ALIAS_XPATH/ALIAS_ID \
   $ALIAS_XPATH/IP \
   $ALIAS_XPATH/NAME \
   $ALIAS_XPATH/PARENT_ID \
)
unset i
VM_ID="${XE[i++]}"
A_ID="${XE[i++]}"
A_IP="${XE[i++]}"
A_NAME="${XE[i++]}"
A_PARENT_ID="${XE[i++]}"

if [ -z "$A_IP" ]; then
    logger -t "$me" -- "No alias IP. exit 0"
    exit 0
fi

# Get primary interface info
unset i XE
NIC_XPATH="/VM/TEMPLATE/NIC[NIC_ID=\"$A_PARENT_ID\"]"
while IFS= read -r -d '' element;do
    XE[i++]="$element"
done < <(base64 -d "$tmpb64" | $XPATH --stdin \
   $NIC_XPATH/IP \
   $NIC_XPATH/VN_MAD \
   $NIC_XPATH/ALIAS_IDS \
)
unset i
NIC_IP="${XE[i++]}"
NIC_VN_MAD="${XE[i++]}"
NIC_ALIAS_IDS="${XE[i++]}"

if [ -n "${NIC_VN_MAD/fw/}" ]; then
    logger -t "$me" -- "NIC VN_MAD not 'fw' but '$NIC_VN_MAD'. exit 0"
    exit 0
fi
#logger -t nic_sp_hook -- "NIC [IP=$NIC_IP, VN_MAD=$NIC_VN_MAD, ALIAS_IDS='$NIC_ALIAS_IDS']"

A_IDX="${A_NAME#*ALIAS}"

attach=
for idx in ${NIC_ALIAS_IDS//,/ }; do
    if [ -n "$DEBUG" ]; then
        logger -t "$me" -- "idx:$idx A_IDX:$A_IDX"
    fi
    if [ "$idx" = "$A_IDX" ]; then
        attach=1
    fi
done

chain="one-${VM_ID}-${A_PARENT_ID}-ip-spoofing"

if [ -n "$attach" ]; then
    # alias add - ADD ipset
    sudo ipset -exist add "$chain" "$A_IP"
    ret=$?
    if [ $ret -ne 0 ]; then
        logger -t "$me" -- "VM $VM_ID NIC_ALIAS[ID=$A_ID, IP=$A_IP, PARENT=$A_PARENT_ID] ipset ADD failed ($ret)"
        sudo ipset save | grep "$chain" >"/tmp/${me}-${ts}-${chain}.ADD"
    elif [ -n "$DEBUG" ]; then
        logger -t "$me" -- "VM $VM_ID add $chain $A_IP ($ret)"
    fi
else
    # alias deleted - DEL ipset
    sudo ipset -exist del "$chain" "$A_IP"
    ret=$?
    if [ $ret -ne 0 ]; then
        logger -t "$me" -- "VM $VM_ID NIC_ALIAS[ID=$A_ID, IP=$A_IP, PARENT_ID=$A_PARENT_ID] ipset DEL failed ($ret)"
        sudo ipset save |grep "$chain" >"/tmp/${me}-${ts}-${chain}.DEL"
    elif [ -n "$DEBUG" ]; then
        logger -t "$me" -- "VM $VM_ID del $chain $A_IP ($ret)"
    fi
fi
exit 0
