#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2018, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# clone fe:SOURCE host:remote_system_ds/disk.i size
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get clone arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC="$1"
DST="$2"
VM_ID="$3"
DS_ID="$4"

TM_PATH="$(dirname $0)"
source "${TM_PATH}/storpool_common.sh"

splog "SRC=$SRC DST=$DST VM_ID=$VM_ID DS_ID=$DS_ID"

DST_HOST=`arg_host $DST`
DST_PATH=`arg_path $DST`
DST_DIR=`dirname $DST_PATH`

DISK_ID=$(echo ${DST##*/} | awk -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "$DS_ID"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "$VM_ID" "$DISK_ID"

#-------------------------------------------------------------------------------
# Compute variables
#-------------------------------------------------------------------------------

SRC_PATH=`arg_path $SRC`
SP_PARENT=${SRC_PATH##*/}
SP_SNAP="${SRC_PATH##*/}-${DISK_ID}"
SP_VOL="${SP_PARENT}-${VM_ID}-${DISK_ID}"
SP_LINK="/dev/storpool/$SP_VOL"

if boolTrue "$NO_VOLUME_TEMPLATE" "NO_VOLUME_TEMPLATE"; then
    SP_TEMPLATE=
else
    SP_TEMPLATE="${ONE_PX}-ds-$DS_ID"
fi

#-------------------------------------------------------------------------------
# Action
#-------------------------------------------------------------------------------

storpoolVolumeDelete "$SP_VOL"

storpoolVolumeClone "$SP_PARENT" "$SP_VOL" "$SP_TEMPLATE"

if [ -n "$SIZE" ]; then
    if [ $SIZE -gt ${ORIGINAL_SIZE:-0} ]; then
        storpoolVolumeResize "$SP_VOL" "$SIZE"M
    fi
fi

storpoolVolumeAttach "$SP_VOL" "$DST_HOST"

storpoolVolumeTag "$SP_VOL" "$VM_ID"

#-------------------------------------------------------------------------------
# Get SYSTEM Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "$VM_DS_ID"

MONITOR_TM_MAD=
if ! boolTrue "$DS_SHARED" "DS_SHARED"; then
    MONITOR_TM_MAD="$DS_TM_MAD"
fi
if [ "${DS_TM_MAD:0:8}" = "storpool" ] && [ "${SP_SYSTEM^^}" = "SSH" ]; then
    MONITOR_TM_MAD="$DS_TM_MAD"
fi

oneSymlink "$DST_HOST" "$SP_LINK" "$DST_PATH"

splog "END $VM_ID"
exit 0
