#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015, StorPool (storpool.com)                                    #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# clone fe:SOURCE host:remote_system_ds/disk.i size
#-------------------------------------------------------------------------------

TM_PATH="$(dirname $0)"

source "${TM_PATH}/storpool_common.sh"

#-------------------------------------------------------------------------------
# Get clone arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

splog "SRC=$SRC DST=$DST VM_ID=$VM_ID DS_ID=$DS_ID"

DST_HOST=`arg_host $DST`
DST_PATH=`arg_path $DST`
DST_DIR=`dirname $DST_PATH`

DISK_ID=$(echo ${DST##*/} | awk -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "$VM_ID" "$DISK_ID"

#-------------------------------------------------------------------------------
# Compute the destination image name
#-------------------------------------------------------------------------------

SRC_PATH=`arg_path $SRC`
SP_PARENT=${SRC_PATH##*/}
SP_SNAP="${SRC_PATH##*/}-${DISK_ID}"
SP_VOL="${SP_PARENT}-${VM_ID}-${DISK_ID}"
SP_TEMPLATE="${SRC_PATH%%/*}"

#-------------------------------------------------------------------------------
# Clone the image
#-------------------------------------------------------------------------------

torpoolAction "CLONE" "$SRC_HOST" "$DST_HOST" "$SP_VOL" "$DST_PATH" "$SP_PARENT" "$SP_TEMPLATE"

splog "END"
exit 0
