#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2016, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# context context.sh file1 file2 ... fileN host:remote_system_ds/disk.i vmid dsid
#   - context.sh file are the contents of the context ISO
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (system)

#-------------------------------------------------------------------------------
# Get context arguments from OpenNebula core
#-------------------------------------------------------------------------------


ARGV=("$@")

DS_ID="${ARGV[$(($#-1))]}"
VM_ID="${ARGV[$(($#-2))]}"
DST="${ARGV[$(($#-3))]}"
SRC=("${ARGV[@]:0:$(($#-3))}")

TM_PATH="$(dirname $0)"
source "${TM_PATH}/storpool_common.sh"

splog "DS_ID=$DS_ID VM_ID=$VM_ID DST=$DST SRC=$SRC"

function exit_error
{
    error_message "$ERROR"
    splog "$ERROR"
    [ -d "$ISO_DIR" ] && rm -rf "$ISO_DIR" > /dev/null 2>&1
    exit -1
}

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "$DS_ID"

if booltTrue "$AUTO_TEMPLATE"; then
    if [ "$SP_PLACEALL" = "" ]; then
        error_message "Datastore template missing 'SP_PLACEALL' attribute."
        exit -1
    fi
    if [ "$SP_PLACETAIL" = "" ]; then
        SP_PLACETAIL="$SP_PLACEALL"
    fi
    if [ -n "${SP_REPLICATION/[123]/}" ] || [ -n "${SP_REPLICATION/[[:digit:]]/}" ]; then
        error_message "Datastore template with unknown value for 'SP_REPLICATION' attribute '$SP_REPLICATION'."
        exit -1
    fi
fi

#-------------------------------------------------------------------------------
# Set dst path and dirs
#-------------------------------------------------------------------------------

DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

DISK_ID=$(echo $DST | awk -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Build the Context Block device (locally) and copy it remotely
#-------------------------------------------------------------------------------

log "Generating context block device"

ISO_DIR="$DS_DIR/.isofiles/$VM_ID"
ISO_FILE="$ISO_DIR/$VM_ID.iso"

exec_and_set_error "mkdir -p $ISO_DIR" \
    "Could not create tmp dir to make context dev"
[ -n "$ERROR" ] && exit_error

for f in "${SRC[@]}"; do
    case "$f" in
    http://*)
        exec_and_set_error "$WGET -P '$ISO_DIR' $f" "Error downloading $f"
        ;;
    *)
        if echo "$f" | grep -q ':'; then
            target=$(echo "$f"|cut -d':' -f2-)
            target="'$target'"
            f=$(echo "$f"|cut -d':' -f1)
        else
            target=""
        fi

        exec_and_set_error "cp -R $f $ISO_DIR/$target" \
            "Error copying $f to $ISO_DIR"
        ;;
    esac

    [ -n "$ERROR" ] && exit_error
done

exec_and_set_error "$MKISOFS -o $ISO_FILE -V CONTEXT -J -R $ISO_DIR" \
    "Error creating iso fs"
[ -n "$ERROR" ] && exit_error

SP_SIZE=$(du -b $ISO_FILE | cut -f1)
SP_SIZE=$(( (SP_SIZE +511) /512 *512 ))
SP_VOL="one-sys-${VM_ID}-${DISK_ID}-iso"
SP_LINK="/dev/storpool/$SP_VOL"
SP_TEMPLATE="one-ds-$DS_ID"

CREATE_CONTEXT_ISO=1
skip_context="/tmp/one-${VM_ID}-${DISK_ID}-iso.skip"
if [ -f "$skip_context" ]; then
    skip_context_ts="$(<"$skip_context")"
    rm -f "$skip_context"
    if storpoolVolumeExists "$SP_VOL"; then
        CREATE_CONTEXT_ISO=0
    fi
fi

if boolTrue "$CREATE_CONTEXT_ISO" ]; then
    storpoolVolumeDelete "$SP_VOL" "force"

    storpoolTemplate "$SP_TEMPLATE"

    storpoolVolumeCreate "$SP_VOL" "$SP_SIZE" "$SP_TEMPLATE"

    #-------------------------------------------------------------------------------
    # Import image to the context volume
    #-------------------------------------------------------------------------------

    if [ -n "$BRIDGE_LIST" ]; then
        storpoolVolumeAttach "$SP_VOL" "$DST_HOST"
        PIPE_CMD="cat $ISO_FILE"
        splog "eval $PIPE_CMD | $SSH $DST_HOST $DD of=/dev/storpool/$SP_VOL bs=512k conv=fdatasync status=none"
        exec_and_log "eval $PIPE_CMD | $SSH $DST_HOST $DD of=/dev/storpool/$SP_VOL bs=512k" \
                 "Error importing $ISO_FILE to $DST_HOST:/dev/storpool/$SP_VOL"
    else
        storpoolVolumeAttach "$SP_VOL"
        splog "$DD if=$ISO_FILE of=/dev/storpool/$SP_VOL bs=512k conv=fdatasync status=none"
        exec_and_log "$DD if=$ISO_FILE of=/dev/storpool/$SP_VOL bs=512k" \
                 "Error importing $ISO_FILE to /dev/storpool/$SP_VOL"
        storpoolVolumeDetach "$SP_VOL"
    fi
else
    splog "found $skip_context ($skip_context_ts) re-using the context ISO"
fi
#-------------------------------------------------------------------------------
# (re)attach readonly
#-------------------------------------------------------------------------------
storpoolVolumeAttach "$SP_VOL" "$DST_HOST" "ro"

if [ $DS_SHARED != "YES" ] || [ "$SP_SYSTEM" = "ssh" ]; then
    MONITOR_TM_MAD="storpool"
fi

oneSymlink "$DST_HOST" "$SP_LINK" "$DST_PATH" "${DST_PATH}.iso"

#-------------------------------------------------------------------------------
# Remove ISO file and source dir
#-------------------------------------------------------------------------------

rm -rf "$ISO_FILE" > /dev/null 2>&1
rm -rf "$ISO_DIR" > /dev/null 2>&1

splog "END $VM_ID"
exit 0
