#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# cpds host:SOURCE host:DEST vmId datastoreId
#   VM disk save-as image
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get cpds arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC="$1"
DST="$2"
SNAP_ID="$3"
VM_ID="$4"
DS_ID="$5"

TM_PATH="$(dirname "$0")"
# shellcheck source=tm/storpool/storpool_common.sh
source "${TM_PATH}/storpool_common.sh"

splog "SRC=${SRC} DST=${DST} SNAP_ID=${SNAP_ID} VM_ID=${VM_ID} DS_ID=${DS_ID}"

SRC_HOST="$(arg_host "${SRC}")"
SRC_PATH="$(arg_path "${SRC}")"

DISK_ID=$(echo "${SRC}" | awk -F. '{print $NF}')
SP_VOL="${DST##*/}"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "${VM_ID}" "${DISK_ID}"

oneImageQc "${IMAGE_ID}"

#-------------------------------------------------------------------------------
# Get Image Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "${DS_ID}"
IMAGE_DS_SP_QOSCLASS="${DS_SP_QOSCLASS}"

SP_QOSCLASS="${IMAGE_DS_SP_QOSCLASS:-${DEFAULT_QOSCLASS}}"
debug_sp_qosclass

#-------------------------------------------------------------------------------
# Compute the destination image name
#-------------------------------------------------------------------------------
SP_SRC="${SRC_PATH##*/}"

SP_PARENT="${SOURCE##*/}"
if boolTrue "CLONE" || [[ "${TYPE^^}" == "CDROM" ]]; then
    SP_PARENT+="-${VM_ID}-${DISK_ID}"
fi
kvGetUid "${SP_PARENT}" fatal
PARENT_ID="${SP_UID}"

if boolTrue "NO_VOLUME_TEMPLATE"; then
	SP_TEMPLATE=
else
	SP_TEMPLATE="${ONE_PX}-ds-${DS_ID}"
fi

splog "DISK_ID=${DISK_ID} SP_SRC=${SP_SRC} SP_VOL=${SP_VOL} SP_PARENT=${SP_PARENT} PARENT_UID=${PARENT_ID}${SP_TEMPLATE:+ SP_TEMPLATE=${SP_TEMPLATE}}"

#-------------------------------------------------------------------------------
# Take snapshot of the image
#-------------------------------------------------------------------------------

if [[ "${SNAP_ID}" == "-1" ]]; then
    if boolTrue "DISK_SAVEAS_FSFREEZE"; then
        oneFsfreeze "${SRC_HOST}" "${DEPLOY_ID}"
        trapAdd "oneFsthaw \"${SRC_HOST}\" \"${DEPLOY_ID}\""
    fi
    storpoolSnapshotCreate "${SP_VOL}" "${PARENT_ID}" \
            "img;${LOC_TAG};virt;qc" \
            "${SP_VOL};${LOC_TAG_VAL};one;${SP_QOSCLASS}"

    if boolTrue "DISK_SAVEAS_FSFREEZE"; then
        oneFsthaw "${SRC_HOST}" "${DEPLOY_ID}"
        trapReset
    fi
else
    SP_SNAPSHOT="${SP_PARENT}-snap${SNAP_ID}"
    kvGetUid "${SP_SNAPSHOT}" fatal
    SNAP_ID="${SP_UID}"
    storpoolVolumeFromSnapshot "${SNAP_ID}" "${SP_VOL}" "${SP_TEMPLATE}"
    storpoolVolumeFreeze "${SP_UID}" "volume"
fi

splog "END ${VM_ID}"
exit 0
