#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2016, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# cpds host:SOURCE host:DEST vmId datastoreId
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get cpds arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC="$1"
DST="$2"
SNAP_ID="$3"
VM_ID="$4"
DS_ID="$5"

TM_PATH="$(dirname $0)"
source "${TM_PATH}/storpool_common.sh"

splog "SRC=$SRC DST=$DST SNAP_ID=$SNAP_ID VM_ID=$VM_ID DS_ID=$DS_ID"

SRC_HOST=`arg_host $SRC`
SRC_PATH=`arg_path $SRC`

DISK_ID=$(echo $SRC | awk -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "$DS_ID"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "$VM_ID" "$DISK_ID"

#-------------------------------------------------------------------------------
# Compute the destination image name
#-------------------------------------------------------------------------------

SP_SRC=${SRC_PATH##*/}
SP_DST="${SP_SRC}-${VM_ID}-${DISK_ID}"
splog "DISK_ID=$DISK_ID SP_DST=$SP_DST"

SP_TEMPLATE="one-ds-$DS_ID"
SP_VOL="${HOTPLUG_SAVE_AS_SOURCE##*/}"
SP_PARENT="${SOURCE##*/}"
if boolTrue "$CLONE"; then
    SP_PARENT+="-${VM_ID}-${DISK_ID}"
fi

#-------------------------------------------------------------------------------
# Take snapshot of the image
#-------------------------------------------------------------------------------

storpoolVolumeDelete "$SP_VOL" "force" "snaps"

oneFsfreeze "$SRC_HOST" "$DEPLOY_ID"
trapAdd "oneFsthaw \"$SRC_HOST\" \"$DEPLOY_ID\""

if [ "$SNAP_ID" = "-1" ]; then
    storpoolVolumeClone "$SP_PARENT" "$SP_VOL" "$SP_TEMPLATE"
else
    SP_PARENT="${SP_PARENT}-snap${SNAP_ID}"
    storpoolSnapshotClone "$SP_PARENT" "$SP_VOL" "$SP_TEMPLATE"
fi

oneFsthaw "$SRC_HOST" "$DEPLOY_ID"
trapReset

splog "END $VM_ID"
exit 0
