#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
# Portions copyright Asociacion Clubs Baloncesto (acb.com)                   #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# failmigrate srcHost dstHost vmPath vmId datasourceId template
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get failmigrate arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC_HOST="$1"
DST_HOST="$2"
VM_PATH="$3"
VM_ID="$4"
DS_ID="$5"
TEMPLATE="$6"
SYSTEM_MAD="$7"

TM_PATH="$(dirname "$0")"
# shellcheck source=tm/storpool/storpool_common.sh
source "${TM_PATH}/storpool_common.sh"

if [[ ! -t 0 ]]; then
    tmpxml="$(mktemp --tmpdir "failmigrate-${VM_ID}-XXXXXXXX")"
    trapAdd APPEND "rm -rf \"${tmpxml}\""
    cat > "${tmpxml}"
    if [[ -s "${tmpxml}" ]]; then
        SYSTEM_MAD="$6"
        TEMPLATE="${tmpxml}"
    fi
fi

if [[ "${SYSTEM_MAD:0:8}" == "storpool" ]]; then
    if boolTrue "DEBUG_MIGRATE_LIVE"; then
        splog "[D] SRC_HOST=${SRC_HOST} DST_HOST=${DST_HOST} VM_PATH=${VM_PATH} VM_ID=${VM_ID} DS_ID=${DS_ID} SYSTEM_MAD=${SYSTEM_MAD} (exit)"
    fi
    exit 0
fi

if boolTrue "MULTICLUSTER"; then
    oneHostInfo "${DST_HOST}"
    DO_MULTICLUSTER=1
    DO_REMOTE="~${HOST_SP_CLUSTER_ID}"
fi

splog "SRC_HOST=${SRC_HOST} DST_HOST=${DST_HOST} VM_PATH=${VM_PATH} VM_ID=${VM_ID} DS_ID=${DS_ID}"

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------
oneDatastoreInfo "${DS_ID}"

MONITOR_TM_MAD=""
if ! boolTrue "DS_SHARED"; then
    MONITOR_TM_MAD="${DS_TM_MAD}"
fi

if [[ "${DS_TM_MAD:0:8}" == "storpool" ]]; then
    if [[ "${SP_SYSTEM^^}" == "SSH" ]]; then
        #-------------------------------------------------------------------------------
        # Cleanup $VM_PATH at DST_HOST
        #-------------------------------------------------------------------------------
        ssh_exec_and_log "${DST_HOST}" "[ -d \"${VM_PATH}\" ] && rm -vrf \"${VM_PATH}\" >/tmp/failmigrate-rm-${VM_ID}.log 2>&1" \
                     "Error Cleaning up ${DST_HOST}:${VM_PATH}"

    fi
fi

#-------------------------------------------------------------------------------
# Get VM information
#-------------------------------------------------------------------------------
oneTemplateInfo "${TEMPLATE}"

#-------------------------------------------------------------------------------
# Detach storpool volumes from DST_HOST
#-------------------------------------------------------------------------------
declare -A volumesToDetach

json=
for i in "${!DISK_ID_ARRAY[@]}"; do
    DISK_ID="${DISK_ID_ARRAY[i]}"
    if [[ "${DISK_TM_MAD_ARRAY[i]}" == "storpool" ]]; then
        DISK_SOURCE="${DISK_SOURCE_ARRAY[i]}"
        if [[ -n "${DISK_SOURCE}" ]]; then
            SP_VOL="${DISK_SOURCE##*/}"
            if boolTrue "DISK_CLONE_ARRAY[i]"; then
                SP_VOL+="-${VM_ID}-${DISK_ID}"
            elif [[ "${DISK_TYPE_ARRAY[i]}" == "CDROM" ]]; then
                SP_VOL+="-${VM_ID}-${DISK_ID}"
            fi
            volumesToDetach["${SP_VOL}"]="${SP_VOL}"
        fi
    fi
done

if [[ "${DS_TM_MAD:0:8}" == "storpool" ]]; then
    #-------------------------------------------------------------------------------
    # Detach volatile disk volumes from DST_HOST
    #-------------------------------------------------------------------------------
    for i in "${!DISK_ID_ARRAY[@]}"; do
        DISK_ID=${DISK_ID_ARRAY[i]}
        if [[ -z ${DISK_TM_MAD_ARRAY[i]} ]] || [[ -z ${DISK_SOURCE_ARRAY[i]} ]]; then
            SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID}"
            volumesToDetach["${SP_VOL}"]="${SP_VOL}"
        fi
    done

    #-------------------------------------------------------------------------------
    # Detach context ISO volume from DST_HOST
    #-------------------------------------------------------------------------------
    DISK_ID=${CONTEXT_DISK_ID}
    if [[ -n "${DISK_ID}" ]]; then
        SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID}"
        volumesToDetach["${SP_VOL}"]="${SP_VOL}"
    fi

    #-------------------------------------------------------------------------------
    # Detach NVRAM volume from DST_HOST
    #-------------------------------------------------------------------------------
    if [[ -n "${T_OS_NVRAM}" ]]; then
        SP_VOL="${ONE_PX}-sys-${VM_ID}-NVRAM"
        volumesToDetach["${SP_VOL}"]="${SP_VOL}"
    fi
    #-------------------------------------------------------------------------------
    # Call the other storage drivers
    #-------------------------------------------------------------------------------
    if declare -f migrate_other >/dev/null; then
        migrate_other "$@"
    fi
fi

forceDetachOther "${VM_ID}" "${SRC_HOST}" "${volumesToDetach[*]}"

splog "END ${VM_ID}"
exit 0
