#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2016, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
# Portions copyright Asociacion Clubs Baloncesto (acb.com)                   #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# failmigrate srcHost dstHost vmPath vmId datasourceId template
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get failmigrate arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC_HOST="$1"
DST_HOST="$2"
VM_PATH="$3"
VM_ID="$4"
DS_ID="$5"
TEMPLATE="$6"

TM_PATH="$(dirname $0)"
for _PATH in "$TM_PATH/"{,../storpool,../../storpool}; do
    if [ -f "${_PATH}/storpool_common.sh" ]; then
        source "${_PATH}/storpool_common.sh"
        break;
    fi
done

splog "SRC_HOST=$SRC_HOST DST_HOST=$DST_HOST VM_PATH=$VM_PATH VM_ID=$VM_ID DS_ID=$DS_ID"

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------
oneDatastoreInfo "$DS_ID"

if [ "$DS_SHARED" != "YES" ] || [ "$SP_SYSTEM" = "ssh" ]; then
    #-------------------------------------------------------------------------------
    # Cleanup $VM_PATH at DST_HOST
    #-------------------------------------------------------------------------------
    ssh_exec_and_log "$DST_HOST" "[ -d \"$VM_PATH\" ] && rm -rf \"$VM_PATH\"" \
                 "Error Cleaning up $DST_HOST:$VM_PATH"
fi

#-------------------------------------------------------------------------------
# Get VM information
#-------------------------------------------------------------------------------
oneTemplateInfo "$TEMPLATE"

#-------------------------------------------------------------------------------
# Detach storpool volumes from DST_HOST
#-------------------------------------------------------------------------------
for i in ${!DISK_ID_ARRAY[@]}; do
    if [ "${DISK_TM_MAD_ARRAY[i]}" = "storpool" ]; then
        DISK_ID="${DISK_ID_ARRAY[i]}"
        DISK_SOURCE="${DISK_SOURCE_ARRAY[i]}"
        if [ -n "$DISK_SOURCE" ]; then
            SP_VOL="${DISK_SOURCE##*/}"
            if [ "${DISK_CLONE_ARRAY[i]}" = "YES" ]; then
                SP_VOL+="-${VM_ID}-${DISK_ID_ARRAY[i]}"
            fi
            DST_PATH="$VM_PATH/disk.${DISK_ID}"
            storpoolVolumeDetach "$SP_VOL" "force" "$DST_HOST" "none" "${DISK_READONLY_ARRAY[i]}"
        else
            if [ -n "$DEBUG_MIGRATE_LIVE" ]; then
                splog "skip volatile disk for $DS_ID/$VM_ID/disk.${DISK_ID}"
            fi
        fi
    fi
done

if [ "${DS_TM_MAD:0:8}" = "storpool" ]; then
    #-------------------------------------------------------------------------------
    # Detach volatile disk volumes from DST_HOST
    #-------------------------------------------------------------------------------
    for i in ${!DISK_ID_ARRAY[@]}; do
        if [ "${DISK_TM_MAD_ARRAY[i]}" = "" ] || [ "${DISK_SOURCE_ARRAY[i]}" = "" ]; then
            FORMAT="${DISK_FORMAT_ARRAY[i]:-raw}"
            if [ ${DISK_TYPE_ARRAY[i]} = "swap" ]; then
                FORMAT="swap"
            fi
            SP_VOL="one-sys-${VM_ID}-${DISK_ID_ARRAY[i]}-${FORMAT}"
            DST_PATH="${VM_PATH}/disk.${DISK_ID_ARRAY[i]}"
            storpoolVolumeDetach "$SP_VOL" "force" "$DST_HOST"
        fi
    done

    #-------------------------------------------------------------------------------
    # Detach context ISO volume from DST_HOST
    #-------------------------------------------------------------------------------
    SP_VOL="one-sys-${VM_ID}-${_CONTEXT_DISK_ID}-iso"
    DST_PATH="$VM_PATH/disk.${_CONTEXT_DISK_ID}"
    storpoolVolumeDetach "$SP_VOL" "force" "$DST_HOST"

    #-------------------------------------------------------------------------------
    # Call the other storage drivers
    #-------------------------------------------------------------------------------
    if declare -f migrate_other >/dev/null; then
        migrate_other "$@"
    fi
fi

splog "END $VM_ID"
exit 0
