#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2018, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# ln host:datastore/image host:remote_system_ds/disk.i vmId datastoreId
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get ln arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC="$1"
DST="$2"
VM_ID="$3"
DS_ID="$4"

TM_PATH="$(dirname $0)"
source "${TM_PATH}/storpool_common.sh"

splog "SRC=$SRC DST=$DST VM_ID=$VM_ID DS_ID=$DS_ID"

#-------------------------------------------------------------------------------
# Do nothing if src and dst are same
#-------------------------------------------------------------------------------

if [ "$SRC" = "$DST" ]; then
    log "Not moving $SRC to $DST, they are the same path"
    splog "END same path"
    exit 0
fi

log "vm $VM_ID moving $SRC to $DST"

#-------------------------------------------------------------------------------
# Process source and destination
#-------------------------------------------------------------------------------

SRC_PATH=`arg_path $SRC`
SRC_HOST=`arg_host $SRC`
DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

DISK_ID=$(echo "$DST_PATH" | $AWK -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Get IMAGE Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "$DS_ID"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "$VM_ID" "$DISK_ID"

SP_VOL="${SOURCE##*/}"
if boolTrue "$NO_VOLUME_TEMPLATE" "NO_VOLUME_TEMPLATE"; then
    SP_TEMPLATE=
else
    SP_TEMPLATE="${ONE_PX}-ds-$DS_ID"
fi

splog "SP_VOL=$SP_VOL SP_TEMPLATE=$SP_TEMPLATE"

#-------------------------------------------------------------------------------
# Enable the destination device
#-------------------------------------------------------------------------------

if [ -n "$SIZE" ]; then
    if [ $SIZE -gt ${ORIGINAL_SIZE:-0} ]; then
        if boolTrue "$CLONE"; then
            storpoolVolumeResize "$SP_VOL" "$SIZE"M
        else
            splog "not resizing Non-CLONED $SP_VOL SIZE=$SIZE ORIGINAL_SIZE=$ORIGINAL_SIZE"
        fi
    fi
fi

if boolTrue "${READONLY}"; then
    SP_MODE="ro"
fi

if [ "$TYPE" = "CDROM" ]; then
    CDROM_VOL="${SP_VOL}-${VM_ID}-${DISK_ID}"
    if ! storpoolVolumeExists "$CDROM_VOL"; then
        storpoolVolumeClone "$SP_VOL" "$CDROM_VOL" "$SP_TEMPLATE"
        storpoolVolumeTag "$CDROM_VOL" "CDROM" "type"
    fi
    SP_VOL="$CDROM_VOL"
else
    storpoolVolumeDetach "$SP_VOL" "force" "" "all"
fi

storpoolVolumeAttach "$SP_VOL" "$DST_HOST" "$SP_MODE"

storpoolVolumeTag "$SP_VOL" "$VM_ID"

#-------------------------------------------------------------------------------
# Get SYSTEM Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "$VM_DS_ID"

MONITOR_TM_MAD=
if ! boolTrue "$DS_SHARED" "DS_SHARED"; then
    MONITOR_TM_MAD="$DS_TM_MAD"
fi
if [ "${DS_TM_MAD:0:8}" = "storpool" ] && [ "${SP_SYSTEM^^}" = "SSH" ]; then
    MONITOR_TM_MAD="$DS_TM_MAD"
fi

oneSymlink "$DST_HOST" "/dev/storpool/$SP_VOL" "$DST_PATH"

splog "END $VM_ID"
exit 0
