#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# mkimage size format host:remote_system_ds/disk.i vmid dsid
#   - size in MB of the image
#   - format for the image
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

#-------------------------------------------------------------------------------
# Get mkimage arguments from OpenNebula core
#-------------------------------------------------------------------------------

SIZE="$1"
FSTYPE="$2"
DST="$3"
VM_ID="$4"
DS_ID="$5"

DRIVER_PATH="$(dirname "$0")"
# shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/storpool_common.sh"

# shellcheck source=/dev/null
source "${DRIVER_PATH}/../../datastore/libfs.sh"

if [[ -f "${DRIVER_PATH}/../../etc/datastore/datastore.conf" ]]; then
    # shellcheck source=/dev/null
    source "${DRIVER_PATH}/../../etc/datastore/datastore.conf"
fi

splog "SIZE=${SIZE} FSTYPE=${FSTYPE} DST=${DST} VM_ID=${VM_ID} DS_ID=${DS_ID}${SUPPORTED_FS:+ SUPPORTED_FS=${SUPPORTED_FS}}${FS_OPTS:+ FS_OPTS=${FS_OPTS}}"

if [[ "${FSTYPE,,}" != "raw" ]] && [[ "${FSTYPE,,}" != "swap" ]]; then
    msg="Unsupported FSTYPE '${FSTYPE}'! Please use 'raw'."
    log_error "${msg}"
    splog "${msg}"
    exit 1
fi

#-------------------------------------------------------------------------------
# Get template information from datastore TEMPLATE definition
#-------------------------------------------------------------------------------

oneDatastoreInfo "${DS_ID}"

#-------------------------------------------------------------------------------
# Set dst path and dirs
#-------------------------------------------------------------------------------

DST_PATH=$(arg_path "${DST}")
DST_HOST=$(arg_host "${DST}")

DISK_ID=$(echo "${DST}" | awk -F. '{print $NF}')

oneVmInfo "${VM_ID}" "${DISK_ID}"

if [[ -n "${DRIVER}" ]] && [[ "${DRIVER,,}" != "raw" ]]; then
    msg="Unsupported DRIVER format '${DRIVER}'! Please use 'raw'."
    log_error "${msg}"
    splog "${msg}"
    exit 1
fi

SP_QOSCLASS="${VM_DISK_SP_QOSCLASS:-${VM_SP_QOSCLASS:-${DS_SP_QOSCLASS:-${DEFAULT_QOSCLASS}}}}"
debug_sp_qosclass

if boolTrue "MULTICLUSTER"; then
   oneHostInfo "${DST_HOST}"
   DO_REMOTE="~${HOST_SP_CLUSTER_ID}"
fi

#-------------------------------------------------------------------------------
# Create image
#-------------------------------------------------------------------------------

SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID}"
SP_TEMPLATE="${ONE_PX}-ds-${DS_ID}"

if storpoolVolumeExists "${SP_VOL}" byName; then
    storpoolDelete "${SP_UID}" "force"
    splog "Delete ${SP_UID} (${SP_VOL}) ($?)"
fi

storpoolVolumeCreate "${SP_VOL}" "$((SIZE*1024*1024))" "${SP_TEMPLATE}" \
    "diskid;${VM_TAG};fs;type;${VC_POLICY:+vc-policy};${SP_QOSCLASS:+qc}" \
    "${DISK_ID};${VM_ID};${FS};VOL${FSTYPE^^};${VC_POLICY};${SP_QOSCLASS}"

VOL_UID="${SP_UID}"
SP_LINK="/dev/storpool-byid/${VOL_UID#*~}"

if [[ -n ${FS} ]]; then
    if type -t contains &>/dev/null; then
        if contains "${SUPPORTED_FS}" "${FS}" ","; then
            splog "FS:'${FS}' is SUPPORTED_FS:${SUPPORTED_FS}"
        else
            splog "FS:'${FS}' not in SUPPORTED_FS:${SUPPORTED_FS}"
            FS=
        fi
    else
        FS=
    fi
fi

storpoolAttach "${VOL_UID}" "${DST_HOST}"

if [[ "${FSTYPE,,}" != "raw" ]] || [[ -n "${FS}" ]]; then
    if [[ "${FSTYPE}" == "swap" ]]; then
        MKFS_CMD="${MKSWAP:-mkswap} -L swap \"${SP_LINK}\""
    else
        if [[ -n "${FS}" ]]; then
            FS_OPTS="FS_OPTS_${FS}"
            MKFS_CMD="${MKFS:-mkfs} -F -t \"${FS}\" ${!FS_OPTS} \"${SP_LINK}\""
        else
            MKFS_CMD="$(mkfs_command "${SP_LINK}" "${FSTYPE}" "${SIZE}")"
        fi
    fi
    splog "MKFS_CMD=${MKFS_CMD}"

    trapAdd "splog \"return \$? \"; storpoolDetach \"${VOL_UID}\" \"force\" \"\" \"all\"; storpoolDelete \"${VOL_UID}\" force snaps"

    splog "ssh_exec_and_log ${DST_HOST} ${MKFS_CMD}"
    ssh_exec_and_log "${DST_HOST}" "${MKFS_CMD}" \
            "Error running ${MKFS_CMD} on ${DST_HOST}"

    trapReset
fi

mode="rw"
type="VOL"
if boolTrue "READONLY"; then
    mode="${READONLY_MODE,,}"
    type+="RO"
fi

if [[ -z "${ON_HOST}" ]] || [[ "${mode}" == "ro" ]]; then
    storpoolAttach "${VOL_UID}" "${DST_HOST}" "${mode}"
fi

storpoolVolumeTag "${VOL_UID}" \
    "virt;${LOC_TAG:-nloc};${VM_TAG:-nvm};${VC_POLICY:+vc-policy};${SP_QOSCLASS:+qc};type;diskid" \
    "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};${SP_QOSCLASS};${type};${DISK_ID}"

MONITOR_TM_MAD=""
if ! boolTrue "DS_SHARED"; then
    MONITOR_TM_MAD="storpool"
fi

oneSymlink "${DST_HOST}" "${VOL_UID}" "${DST_PATH}"

splog "END ${VM_ID}"
exit 0
