#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2020, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# mkswap size host:remote_system_ds/disk.i size vmid dsid
#   - size in MB of the image
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

#-------------------------------------------------------------------------------
# Get mkswap arguments from OpenNebula core
#-------------------------------------------------------------------------------

SIZE="$1"
DST="$2"
VM_ID="$3"
DS_ID="$4"

DRIVER_PATH="$(dirname $0)"
source "${DRIVER_PATH}/storpool_common.sh"

splog "SIZE=$SIZE DST=$DST VM_ID=$VM_ID DS_ID=$DS_ID"

$DRIVER_PATH/mkimage "$SIZE" "swap" "$DST" "$VM_ID" "$DS_ID"
