#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015, StorPool (storpool.com)                                    #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# mv host:remote_datastore/disk.i host:remote_datastore/disk.i vmId datastoreId
#-------------------------------------------------------------------------------

TM_PATH="${0%/*}"

source "${TM_PATH}/storpool_common.sh"

#-------------------------------------------------------------------------------
# Get mv arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

splog "SRC=$SRC DST=$DST VM_ID=$VM_ID DS_ID=$DS_ID"

#-------------------------------------------------------------------------------
# Process source and destination
#-------------------------------------------------------------------------------

SRC_PATH=`arg_path $SRC`
SRC_HOST=`arg_host $SRC`
DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

DISK_ID=$(echo "$DST_PATH" | $AWK -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "$VM_ID" "$DISK_ID"

SP_VOL="${SOURCE##*/}"
[ -n "$PERSISTENT" ] || SP_VOL="${SP_VOL}-${VM_ID}-${DISK_ID}"
SP_LINK="/dev/storpool/$SP_VOL"
SP_TEMPLATE="${SOURCE%%/*}"

log "vm $VM_ID moving $SRC to $DST"

#-------------------------------------------------------------------------------
# run only DETACH_CMD on EPILOG_STOP, EPILOG_UNDEPLOY
#-------------------------------------------------------------------------------

if [ $LCM_STATE = "10" ]; then
    DETACH_ONLY="END (LCM_STATE=$LCM_STATE EPILOG_STOP)"
fi
if [ $LCM_STATE = "30" ]; then
    DETACH_ONLY="END (LCM_STATE=$LCM_STATE EPILOG_UNDEPLOY)"
fi

#-------------------------------------------------------------------------------
# Detach source device but keep symlink if migrating
#-------------------------------------------------------------------------------

storpoolAction "DETACH" "$SRC_HOST" "$DST_HOST" "$SP_VOL" "$DST_PATH"

#-------------------------------------------------------------------------------
# Do nothing on EPILOG_STOP, EPILOG_UNDEPLOY
#-------------------------------------------------------------------------------

if [ -n "$DETACH_ONLY" ]; then
    splog "$DETACH_ONLY"
    exit 0
fi

#-------------------------------------------------------------------------------
# Enable the destination device
#-------------------------------------------------------------------------------

storpoolAction "ATTACH" "$SRC_HOST" "$DST_HOST" "$SP_VOL" "$DST_PATH"

splog "END"
exit 0
