#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2016, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# mvds host:remote_system_ds/disk.i host:remote_system_ds/disk.i vmId datastoreId
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get mvds arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC="$1"
DST="$2"
VM_ID="$3"
DS_ID="$4"

TM_PATH="$(dirname $0)"
source "${TM_PATH}/storpool_common.sh"

splog "SRC=$SRC DST=$DST VM_ID=$VM_ID DS_ID=$DS_ID"

#-------------------------------------------------------------------------------
# Compute the destination image name
#-------------------------------------------------------------------------------

SRC_HOST=`arg_host $SRC`
SRC_PATH=`arg_path $SRC`
SRC_DIR="${SRC_PATH%/*}"
DST_HOST=`arg_host $SRC`
DST_PATH=`arg_path $SRC`

DISK_ID=$(echo $SRC_PATH | awk -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "$DS_ID"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "$VM_ID" "$DISK_ID"

SP_VOL="${SOURCE##*/}"
if boolTrue "$CLONE"; then
    SP_VOL+="-${VM_ID}-${DISK_ID}"
fi

SP_NEW="${DST##*/}"
if [ "$SP_VOL" != "$SP_NEW" ]; then
    DEFERRED=1
fi

SP_TEMPLATE="${DST%%/*}"

splog "SRC_HOST=$SRC_HOST $SP_VOL ${DEFERRED:+DEFERRED SP_NEW=$SP_NEW SP_TEMPLATE=$SP_TEMPLATE}"

#-------------------------------------------------------------------------------
# Detach and if it is deferred snapshot "convert" to Image
#-------------------------------------------------------------------------------

storpoolVolumeDetach "$SP_VOL" "force" "$SRC_HOST" "all" "$READONLY"

if boolTrue "$DEFERRED"; then
    storpoolVolumeRename "$SP_VOL" "$SP_NEW" "$SP_TEMPLATE"
fi

splog "END $VM_ID"
exit 0
