#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2024, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# mvds host:remote_system_ds/disk.i host:remote_system_ds/disk.i vmId datastoreId
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get mvds arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC="$1"
DST="$2"
VM_ID="$3"
DS_ID="$4"

TM_PATH="$(dirname $0)"
source "${TM_PATH}/storpool_common.sh"

splog "SRC=$SRC DST=$DST VM_ID=$VM_ID DS_ID=$DS_ID"

#-------------------------------------------------------------------------------
# Compute the destination image name
#-------------------------------------------------------------------------------

SRC_HOST=`arg_host $SRC`
SRC_PATH=`arg_path $SRC`
SRC_DIR="${SRC_PATH%/*}"
DST_HOST=`arg_host $SRC`
DST_PATH=`arg_path $SRC`

DISK_ID=$(echo $SRC_PATH | awk -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "$DS_ID"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "$VM_ID" "$DISK_ID"

SP_VOL="${SOURCE##*/}"
if boolTrue "CLONE"; then
    SP_VOL+="-${VM_ID}-${DISK_ID}"
fi

SP_NEW="${DST##*/}"
if [ "$SP_VOL" != "$SP_NEW" ]; then
    DEFERRED=1
fi

if boolTrue "NO_VOLUME_TEMPLATE"; then
    SP_TEMPLATE=
else
    SP_TEMPLATE="${ONE_PX}-ds-$DS_ID"
fi

SP_QOSCLASS=$(oneImageQc "${IMAGE_ID}")
SP_QOSCLASS=${SP_QOSCLASS:-${DEFAULT_SP_QOSCLASS}}

splog "SRC_HOST=$SRC_HOST $SP_VOL ${DEFERRED:+DEFERRED SP_NEW=$SP_NEW SP_TEMPLATE=$SP_TEMPLATE}${SP_QOSCLASS:+ SP_QOSCLASS=${SP_QOSCLASS}}${SHAREABLE:+ SHAREABLE=$SHAREABLE}"

#-------------------------------------------------------------------------------
# Detach and if it is deferred OpenNebula snapshot "convert" to Image
#-------------------------------------------------------------------------------

if boolTrue "SHAREABLE"; then
    shareableDetach "$SRC_HOST" "${IMAGE_DS_ID}/${IMAGE_ID}/${VM_ID}/${DISK_ID}/${SP_VOL}"
else
    storpoolVolumeDetach "$SP_VOL" "force" "$SRC_HOST" "all" "$READONLY"

    storpoolVolumeTag "$SP_VOL" ";;${SP_QOSCLASS}" "$VM_TAG;vc-policy;qc"

    if boolTrue "DEFERRED"; then
        storpoolVolumeRename "$SP_VOL" "$SP_NEW" "$SP_TEMPLATE"
    fi

    if boolTrue "VMSNAPSHOT_DELETE_ON_TERMINATE"; then
        storpoolVolumeSnapshotsDelete "${SP_VOL}-${VMSNAPSHOT_TAG}-"
    fi
fi

splog "deleting $SRC_PATH on $SRC_HOST"
ssh_exec_and_log "$SRC_HOST" "rm -vf ${SRC_PATH}*" \
            "Error deleting $SRC_PATH on $SRC_HOST"

splog "END $VM_ID"
exit 0
