#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015, StorPool (storpool.com)                                    #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
# Portions copyright Asociacion Clubs Baloncesto (acb.com)                   #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# postmigrate srcHost dstHost vmPath vmId datasourceId template
#-------------------------------------------------------------------------------

TM_PATH="`dirname $0`"

for _PATH in "$TM_PATH/"{,../storpool,../../storpool}; do
    if [ -f "${_PATH}/storpool_common.sh" ]; then
        source "${_PATH}/storpool_common.sh"
        break;
    fi
done

#-------------------------------------------------------------------------------
# Get cmd arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC_HOST=$1
DST_HOST=$2
VM_PATH=$3
VM_ID=$4
DS_ID=$5
TEMPLATE=$6

splog "SRC_HOST=$SRC_HOST DST_HOST=$DST_HOST VM_PATH=$VM_PATH VM_ID=$VM_ID DS_ID=$DS_ID"

oneDatastoreInfo "$DS_ID"

oneTemplateInfo "$TEMPLATE"

for i in ${!DISK_TM_MAD_ARRAY[@]}; do
    if [ "${DISK_TM_MAD_ARRAY[i]}" = "storpool" ]; then
        DISK_SOURCE="${DISK_SOURCE_ARRAY[i]}"
        SP_VOL="${DISK_SOURCE##*/}"
        [ -n "${DISK_PERSISTENT_ARRAY[i]}" ] || SP_VOL+="-${VM_ID}-${DISK_ID_ARRAY[i]}"

        DST_PATH="$VM_PATH/disk.${DISK_ID_ARRAY[i]}"
        storpoolAction "DETACH_HERE" "$SRC_HOST" "$DST_HOST" "$SP_VOL" "$DST_PATH"
    fi
done

if [ "$DS_SHARED" != "YES" ]; then
    #-------------------------------------------------------------------------------
    # Cleanup src VM files from the src host
    #-------------------------------------------------------------------------------

    CMD="$SSH $SRC_HOST 'rm -rf $VM_PATH'"
    exec_and_log "eval $CMD" "Error removing $VM_PATH"
fi

splog "END"
exit 0
