#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

DRIVER_PATH="$(dirname "${0}")"

#shellcheck source=/dev/null
source "${DRIVER_PATH}/../../scripts_common.sh"
#shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/storpool_common.sh"

splog "${*}"

if [[ -t 0 ]]; then
    msg="Interactive mode not supported"
    splog "${msg}"
    error_message "${msg}"
    exit 1
fi

KVMHOST="${1%%:*}"
VMDIR="${1#*:}"
DISKS="$2"
DEPLOY_ID="$3"
VM_ID="$4"
SYSDS_ID="$5"
if [[ -n "$6" ]]; then
    BJ_ID="$4"
    VM_ID="$5"
    SYSDS_ID="$6"
fi
export DISKS BJ_ID

B_DIR="${VMDIR}/backup"

if boolTrue "DEBUG_POSTBACKUP"; then
    splog "${KVMHOST} ${VMDIR} ${DISKS} ${DEPLOY_ID}${BJ_ID:+ ${BJ_ID}} ${VM_ID} ${SYSDS_ID}"
fi

oneDatastoreInfo "${SYSDS_ID}"

oneHostInfo "${KVMHOST}"

VM_XML="$(mktemp -t "postbackup-${VM_ID}-XXXXXXXX")"
trapAdd "rm -f \"${VM_XML}\""
cat > "${VM_XML}"

if [[ -d "${B_DIR}" ]]; then
    splog "[I] post-clean ${B_DIR} ..."
    snapshots_list="${B_DIR}/.storpool_snapshots"
    if [[ -f ${snapshots_list} ]]; then
        while read -r -u "${spfh}" volume sGlobalId sName; do
            if boolTrue "DEBUG_BACKUP"; then
                splog "[D] Removing snapshot ${sName}(${sGlobalId}) volume ${volume}"
            else
                splog "[I]Removing snapshot ${sName} volume ${volume}"
            fi
            json="{\"snapshot\":\"${sName}\",\"detach\":\"all\",\"force\":true}"
            DO_MULTICLUSTER=1 DO_REMOTE="" storpoolRetry VolumesReassignWait "\"reassign\":[${json}]"
            SKIP_KV_DATA=1 storpoolSnapshotDelete "${sName}"
        done {spfh}< <(cat "${snapshots_list}" || true)
        exec {spfh}<&-
    fi
    rm -rf "${B_DIR}"
    splog "[I] post-clean completed ($?)"
else
    splog "[W] Folder not found. ${B_DIR}"
fi

RCMD=$(cat <<EOF
rm -rf "${B_DIR}"
EOF
)
splog "[I]RCMD ${KVMHOST}::${RCMD}"
ssh_forward ssh_exec_and_log "${KVMHOST}" "${RCMD}" \
                  "Error extracting ${RCMD} on ${KVMHOST}"

splog "END"
