#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
# Portions copyright Asociacion Clubs Baloncesto (acb.com)                   #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# postmigrate srcHost dstHost vmPath vmId datasourceId template
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get postmigrate arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC_HOST="$1"
DST_HOST="$2"
VM_PATH="$3"
VM_ID="$4"
DS_ID="$5"
TEMPLATE="$6"
SYSTEM_MAD="$7"

TM_PATH="$(dirname "${0}")"

#shellcheck source=tm/storpool/storpool_common.sh
source "${TM_PATH}/storpool_common.sh"

if [[ ! -t 0 ]]; then
    tmpxml="$(mktemp --tmpdir "postmigrate-${VM_ID}-XXXXXXXX")"
    trapAdd APPEND "rm -rf \"${tmpxml}\""
    # TEMPLATE_64 is for compatibility with migrate_other()
    TEMPLATE_64="$(tee "${tmpxml}" || true)"
    export TEMPLATE_64
    if [[ -s "${tmpxml}" ]]; then
        SYSTEM_MAD="$6"
        TEMPLATE="${tmpxml}"
    fi
fi

if [[ "${SYSTEM_MAD:0:8}" == "storpool" ]]; then
    if boolTrue "DEBUG_MIGRATE_LIVE"; then
        splog "[D] SRC_HOST=${SRC_HOST} DST_HOST=${DST_HOST} VM_PATH=${VM_PATH} VM_ID=${VM_ID} DS_ID=${DS_ID} SYSTEM_MAD=${SYSTEM_MAD} (exit)"
    fi
    exit 0
fi

if boolTrue "MULTICLUSTER"; then
    oneHostInfo "${SRC_HOST}"
    DO_MULTICLUSTER=1
    DO_REMOTE="~${HOST_SP_CLUSTER_ID}"
fi

splog "SRC_HOST=${SRC_HOST} DST_HOST=${DST_HOST} VM_PATH=${VM_PATH} VM_ID=${VM_ID} DS_ID=${DS_ID} SYSTEM_MAD=${SYSTEM_MAD}"

#-------------------------------------------------------------------------------
# Get SYSTEM Datastore information
#-------------------------------------------------------------------------------
oneDatastoreInfo "${DS_ID}"

#-------------------------------------------------------------------------------
# Get VM information
#-------------------------------------------------------------------------------
oneTemplateInfo "${TEMPLATE}"

#-------------------------------------------------------------------------------
# Detach storpool volumes
#-------------------------------------------------------------------------------
json=""
for i in "${!DISK_ID_ARRAY[@]}"; do
    DISK_ID="${DISK_ID_ARRAY[i]}"
    if [[ "${DISK_TM_MAD_ARRAY[i]:0:8}" == "storpool" ]]; then
        DISK_SOURCE="${DISK_SOURCE_ARRAY[i]}"
        if [[ -n "${DISK_SOURCE}" ]]; then
            SP_VOL="${DISK_SOURCE##*/}"
            if boolTrue "DISK_CLONE_ARRAY[i]"; then
                SP_VOL+="-${VM_ID}-${DISK_ID}"
                disk_type="nonpersistent"
            elif [[ "${DISK_TYPE_ARRAY[i]}" == "CDROM" ]]; then
#                # backward compatibility /clean up/
#                if kvGetUid "${SP_VOL}"; then
#                    splog "BCK VM ${VM_ID} DISK ${DISK_ID} ${SP_VOL} ${SP_UID} RO:${DISK_READONLY_ARRAY[i]}"
#                    storpoolDetach "${SP_UID}" "" "${SRC_HOST}" "none" "${DISK_READONLY_ARRAY[i]}"
#                fi
                SP_VOL+="-${VM_ID}-${DISK_ID}"
                disk_type="cdrom"
            else
                disk_type="persistent"
            fi
            kvGetUid "${SP_VOL}" fatal
            [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}" || true)"
            [[ -z "${json}" ]] || json+=","
            json+="$(storpoolVolumeJsonHelper "${SP_UID}" volume "[${SRC_CLIENT}]" "detach" "force" "${DISK_READONLY_ARRAY[i]}" || true)"
            if boolTrue "DEBUG_MIGRATE_LIVE"; then
                splog "VM ${VM_ID} DISK_ID ${DISK_ID} ${SP_VOL} ${SP_UID} ${disk_type} detach ${SRC_CLIENT}"
            fi
        else
            if boolTrue "DEBUG_MIGRATE_LIVE"; then
                splog "skip volatile disk for ${DS_ID}/${VM_ID}/disk.${DISK_ID} (no DISK/SOURCE)"
            fi
        fi
    fi
done

if [[ "${DS_TM_MAD:0:8}" == "storpool" ]]; then
    #-------------------------------------------------------------------------------
    # Detach volatile disk volumes
    #-------------------------------------------------------------------------------
    for i in "${!DISK_ID_ARRAY[@]}"; do
        DISK_ID="${DISK_ID_ARRAY[i]}"
        if [[ -z "${DISK_TM_MAD_ARRAY[i]}" ]] || [[ -z "${DISK_SOURCE_ARRAY[i]}" ]]; then
            SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID}"
            disk_type="volatile"
            [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}")"
            kvGetUid "${SP_VOL}" fatal
            [[ -z "${json}" ]] || json+=","
            json+="$(storpoolVolumeJsonHelper "${SP_UID}" volume "[${SRC_CLIENT}]" "detach" "force")"
            if boolTrue "DEBUG_MIGRATE_LIVE"; then
                splog "[D] VM ${VM_ID} DISK_ID ${DISK_ID} ${SP_VOL} ${SP_UID} ${disk_type} detach ${SRC_CLIENT}"
            fi
         fi
    done

    [[ -n "${SRC_CLIENT}" ]] || SRC_CLIENT="$(storpoolClientId "${SRC_HOST}" "${COMMON_DOMAIN}")"

    #-------------------------------------------------------------------------------
    # Detach context ISO volume
    #-------------------------------------------------------------------------------
    if [[ -n "${CONTEXT_DISK_ID}" ]]; then
        DISK_ID="${CONTEXT_DISK_ID}"
        SP_VOL="${ONE_PX}-sys-${VM_ID}-${DISK_ID}"
        kvGetUid "${SP_VOL}" fatal
        [[ -z "${json}" ]] || json+=","
        json+="$(storpoolVolumeJsonHelper "${SP_UID}" volume "[${SRC_CLIENT}]" "detach" "force")"
        if boolTrue "DEBUG_MIGRATE_LIVE"; then
            splog "[D] VM ${VM_ID} DISK_ID ${DISK_ID} ${SP_VOL} ${SP_UID} detach ${SRC_CLIENT}"
        fi
    fi

    #-------------------------------------------------------------------------------
    # Detach NVRAM volume
    #-------------------------------------------------------------------------------
    if [[ -n "${T_OS_NVRAM}" ]]; then
        SP_VOL="${ONE_PX}-sys-${VM_ID}-NVRAM"
        kvGetUid "${SP_VOL}" fatal
        [[ -z "${json}" ]] || json+=","
        json+="$(storpoolVolumeJsonHelper "${SP_UID}" volume "[${SRC_CLIENT}]" "detach" "force")"
        if boolTrue "DEBUG_MIGRATE_LIVE"; then
            splog "[D] VM ${VM_ID} ${SP_VOL} ${SP_UID} detach ${SRC_CLIENT}"
        fi
    fi

    #-------------------------------------------------------------------------------
    # Call the other storage drivers
    #-------------------------------------------------------------------------------
    if declare -f migrate_other >/dev/null; then
        migrate_other "$@"
    fi
fi

storpoolRetry VolumesReassignWait "\"reassign\":[${json}]"

MONITOR_TM_MAD=
if ! boolTrue "DS_SHARED"; then
    MONITOR_TM_MAD="${DS_TM_MAD}"
fi

#-------------------------------------------------------------------------------
# Cleanup src VM files from the src host
#-------------------------------------------------------------------------------
if [[ "${DS_TM_MAD:0:8}" == "storpool" ]] && [[ "${SP_SYSTEM^^}" == "SSH" ]]; then
    RM_CMD="${SSH:-ssh} ${SRC_HOST} 'rm -rf ${VM_PATH}'"
    splog "${RM_CMD}"
    exec_and_log "eval ${RM_CMD}" "Error removing ${VM_PATH}"
fi

splog "END ${VM_ID}"
