#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

DRIVER_PATH="$(dirname "$0")"
umask 077

# shellcheck source=/dev/null
source "${DRIVER_PATH}/../../scripts_common.sh"
#shellcheck source=tm/storpool/storpool_common.sh
source "${ONE_LOCATION:-/var/lib/one/remotes}/tm/storpool/storpool_common.sh"

if [[ -t 0 ]]; then
    msg="Interactive mode not supported"
    splog "${msg}"
    error_message "${msg}"
    exit 1
fi

KVMHOST="${1%%:*}"
VMDIR="${1#*:}"
DISKS="$2"
DEPLOY_ID="$3"
VM_ID="$4"
SYSDS_ID="$5"
if [[ -n "$6" ]]; then
    BJ_ID="$4"
    VM_ID="$5"
    SYSDS_ID="$6"
fi
export BJ_ID  #  TBD: remove

splog "${KVMHOST} ${VMDIR} ${DISKS} ${DEPLOY_ID}${BJ_ID:+ ${BJ_ID}} ${VM_ID} ${SYSDS_ID}"

B_DIR="${VMDIR}/backup"

VM_XML="$(mktemp -t "prebackup-${VM_ID}-XXXXXXXX")"
trapAdd "rm -f \"${VM_XML}\""
cat > "${VM_XML}"

oneHostInfo "${KVMHOST}"

oneDatastoreInfo "${SYSDS_ID}"

oneVmVolumes "${VM_ID}" "" "${VM_XML}" "${DISKS}"

SNAPSHOTS_LIST="${B_DIR}/.storpool_snapshots"

if [[ -d "${B_DIR}" ]]; then
    splog "[I] pre-clean ${B_DIR} ..."
    if [[ -f "${SNAPSHOTS_LIST}" ]]; then
        while read -r -u "${spfh}" volume sGlobalId sName; do
            splog "[I] Removing snapshot ${sName}, volume ${volume}"
            json="{\"snapshot\":\"${sName}\",\"detach\":\"all\",\"force\":true}"
            DO_MULTICLUSTER=1 DO_REMOTE="" storpoolRetry VolumesReassignWait "\"reassign\":[${json}]"
            SKIP_KV_DATA=1 storpoolSnapshotDelete "${sName}"
        done {spfh}< <(cat "${SNAPSHOTS_LIST}" || true)
        exec {spfh}<&-
    fi
    rm -rf "${B_DIR}"
    splog "[I] pre-clean completed ($?)"
fi

mkdir -p "${B_DIR}"
splog "mkdir -p ${B_DIR}"

base64 -w 60 "${VM_XML}" >"${B_DIR}/vm.xml"
splog "base64 ${VM_XML} to ${B_DIR}/vm.xml ($?)"

rm -f "${VM_XML}"
trapDel "rm -f \"${VM_XML}\""

declare -A D_ARR
for disk in ${DISKS//:/ }; do
    D_ARR["${disk}"]="${disk}"
done

B_SUFFIX="ONEBACKUP-$(date +%s || true)"
echo "${B_SUFFIX}" >"${B_DIR}/.snapshot_suffix"
declare -a list_a
backups=

json_volumes=""
for map in ${vmDisksMap}; do
    img="${map%:*}"
    did="${map#*:}"
    kvGetUid "${img}" fatal
    if [[ -n "${D_ARR["${did}"]}" ]]; then
        tags=$(tagsHelper "${VM_TAG};${LOC_TAG};virt;img;bak" "${VM_ID};${LOC_TAG_VAL};one;${img};${B_SUFFIX}")
        json_volumes+="${json_volumes:+,}{\"volume\":\"${SP_UID}\",\"tags\":{${tags}}}"
        snapshot="${img}-${B_SUFFIX}"
        list_a+=("${SP_UID}" "${snapshot}")
        backups+="${SP_UID}:${snapshot}:${did} "
    fi
done
json="\"volumes\":[${json_volumes}]"
DO_MULTICLUSTER=1 DO_REMOTE="" storpoolRetry VolumesGroupSnapshot "${json}" >/dev/null
ret=$?
if [[ ${ret} -ne 0 ]]; then
    splog "Error: Can't create volumes group snapshots (${ret})"
    exit 1
fi
while read -r -u "${xfh}" volume snapshotGlobalId snapshotName; do
    echo "${volume} ${snapshotGlobalId} ${snapshotName}" >>"${SNAPSHOTS_LIST}"
done {xfh}< <(jq -r '.data.snapshots[]|"\(.volume) \(.snapshotGlobalId) \(.snapshotName)"' "${TMPDIR}/VolumesGroupSnapshot.json" || true)
exec {xfh}<&-

if [[ -n "${TPM_MODEL}" ]]; then
    oneTpmBackup "${VM_ID}" "${VMDIR}" "${KVMHOST}" "${B_DIR}/disk.tpm.0"
fi

for bak in ${backups}; do
    IFS=: read -r volume snapshot did <<< "${bak}"
    read -r vName sGlobalId sName <<< "$(grep "${volume} " "${SNAPSHOTS_LIST}" || true)"
    if boolTrue "DEBUG_BACKUP"; then
        splog "[D] did=${did} volume=${volume} snapshot=${snapshot} vName=${vName} sGlobalId=${sGlobalId} sName=${sName}"
    fi
    json="{\"snapshot\":\"${sName}\",\"ro\":[${HOST_SP_OURID}]}"
    DO_MULTICLUSTER=1 DO_REMOTE="~${HOST_SP_CLUSTER_ID:-${SP_CLUSTER_ID}}" storpoolRetry VolumesReassignWait "\"reassign\":[${json}]"
    ret=$?
    if [[ ${ret} -ne 0 ]]; then
        splog "[E] Error: Can't attach ${sName} to ${KVMHOST}"
        exit 1
    fi
    snapPath="/dev/storpool-byid/${sGlobalId}"
    dstFile="${B_DIR}/disk.${did}.0"
    RCMD=$(cat <<EOF
umask 077
mkdir -p "${B_DIR}"
qemu-img convert -T none -t none -O qcow2 "${snapPath}" "${dstFile}"
EOF
)
    splog "[I] RCMD ${KVMHOST}::$(echo "${RCMD}" | tr '\n' ';' || true)"
    ssh_forward ssh_exec_and_log "${KVMHOST}" "${RCMD}" "Error extracting ${RCMD} on ${KVMHOST}"
    json="{\"snapshot\":\"${sName}\",\"detach\":\"all\",\"force\":true}"
    DO_MULTICLUSTER=1 DO_REMOTE="" storpoolRetry VolumesReassignWait "\"reassign\":[${json}]"
done

${RSYNC:-rsync} -a "${B_DIR}"/ "${KVMHOST}:${B_DIR}"/
splog "[I] ${RSYNC:-rsync} -a ${B_DIR}/ ${KVMHOST}:${B_DIR}/ ($?)"

splog "END ${VM_ID}"
