#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015, StorPool (storpool.com)                                    #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
# Portions copyright Asociacion Clubs Baloncesto (acb.com)                   #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# premigrate srcHost dstHost vmPath vmId datasourceId template
#-------------------------------------------------------------------------------

TM_PATH="`dirname $0`"

for _PATH in "$TM_PATH/"{,../storpool,../../storpool}; do
    if [ -f "${_PATH}/storpool_common.sh" ]; then
        source "${_PATH}/storpool_common.sh"
        break;
    fi
done

#-------------------------------------------------------------------------------
# Get cmd arguments from OpenNebula core
#-------------------------------------------------------------------------------
SRC_HOST=$1
DST_HOST=$2
VM_PATH=$3
VM_ID=$4
DS_ID=$5
TEMPLATE=$6

splog "SRC_HOST=$SRC_HOST DST_HOST=$DST_HOST VM_PATH=$VM_PATH VM_ID=$VM_ID DS_ID=$DS_ID"

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------
oneDatastoreInfo "$DS_ID"

if [ "$DS_SHARED" != "YES" ] || [ "$SP_SYSTEM" = "ssh" ]; then
    #-------------------------------------------------------------------------------
    # Create DST path
    #-------------------------------------------------------------------------------
    ssh_make_path "$DST_HOST" "$VM_PATH"

    #-------------------------------------------------------------------------------
    # Copy VM related content to dst host.
    #-------------------------------------------------------------------------------
    TAR_COPY="$SSH $SRC_HOST '$TAR -C $VM_PATH --sparse -cf - .'"
    TAR_COPY="$TAR_COPY | $SSH $DST_HOST '$TAR -C $VM_PATH --sparse -xf -'"
    splog "Copy $VM_PATH from $SRC_HOST to $DST_HOST (ssh)"
    exec_and_log "eval $TAR_COPY" "Error copying VM directory to target host $VM_PATH"
fi

#-------------------------------------------------------------------------------
# Get VM information
#-------------------------------------------------------------------------------
oneTemplateInfo "$TEMPLATE"

#-------------------------------------------------------------------------------
# Attach storpool volumes
#-------------------------------------------------------------------------------
for i in ${!DISK_ID_ARRAY[@]}; do
    if [ "${DISK_TM_MAD_ARRAY[i]}" = "storpool" ]; then
        DISK_SOURCE="${DISK_SOURCE_ARRAY[i]}"
        SP_VOL="${DISK_SOURCE##*/}"
        [ -n "${DISK_PERSISTENT_ARRAY[i]}" ] || SP_VOL+="-${VM_ID}-${DISK_ID_ARRAY[i]}"
        DST_PATH="$VM_PATH/disk.${DISK_ID_ARRAY[i]}"
        storpoolAction "ATTACH" "$SRC_HOST" "$DST_HOST" "$SP_VOL" "$DST_PATH"
    fi
done

if [ "$DS_TM_MAD" = "storpool" ]; then
    #-------------------------------------------------------------------------------
    # Attach volatile disk volumes
    #-------------------------------------------------------------------------------
    for i in ${!DISK_ID_ARRAY[@]}; do
        if [ "${DISK_TM_MAD_ARRAY[i]}" = "" ]; then
            FORMAT="${DISK_FORMAT_ARRAY[i]}"
            if [ ${DISK_TYPE_ARRAY[i]} = "swap" ]; then
                FORMAT="swap"
            fi
            SP_VOL="one-sys-${VM_ID}-${DISK_ID_ARRAY[i]}-${FORMAT}"
            DST_PATH="${VM_PATH}/disk.${DISK_ID_ARRAY[i]}"
            storpoolAction "ATTACH" "$SRC_HOST" "$DST_HOST" "$SP_VOL" "$DST_PATH"
        fi
    done

    #-------------------------------------------------------------------------------
    # Attach context ISO volume
    #-------------------------------------------------------------------------------
    SP_VOL="one-sys-${VM_ID}-${_CONTEXT_DISK_ID}-iso"
    DST_PATH="$VM_PATH/disk.${_CONTEXT_DISK_ID}"
    EXTRA_CMD="ln -sf $DST_PATH ${DST_PATH}.iso"
    SP_MODE="ro"
    storpoolAction "ATTACH" "$SRC_HOST" "$DST_HOST" "$SP_VOL" "$DST_PATH"
fi

splog "END"
exit 0
