#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

DRIVER_PATH=$(dirname "$0")

DRV_ACTION="$(cat)"

#shellcheck source=/dev/null
source "${DRIVER_PATH}/../../scripts_common.sh"
#shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/../../tm/storpool/storpool_common.sh"

DEPLOY_ID=$1
FILE=$2
HVHOST=$3
VM_ID=$4
HVHOST2=$5
export HVHOST2  #  TBD: remove

splog "$*"

if boolTrue "SP_CHECKPOINT_BD"; then
    read -r -a DS_ID_A <<< "${FILE//\// }"
    DS_ID="${DS_ID_A[-3]}"
    oneDatastoreInfo "${DS_ID}"

    SP_VOL="${ONE_PX}-sys-${VM_ID}-rawcheckpoint"

    if storpoolVolumeExists "${SP_VOL}"; then
        storpoolVolumeDelete "${SP_VOL}" "force"
    fi
    read -r -a DS_ID_A <<< "${FILE//\// }"
    DS_ID="${DS_ID_A[-3]}"
    _XPATH="${DRIVER_PATH}/../../datastore/xpath.rb"
    declare -a _XPATH_A _XPATH_QUERY
    _XPATH_A=("${_XPATH}" "--stdin")
    _XPATH_QUERY=("/VMM_DRIVER_ACTION_DATA/VM/TEMPLATE/MEMORY")
    VM_MEMORY=$(echo "${DRV_ACTION}" | base64 -d | "${_XPATH_A[@]}" "${_XPATH_QUERY[@]}" || true)
    storpoolVolumeCreate "${SP_VOL}" "$((VM_MEMORY*2))M" "${ONE_PX}-ds-${DS_ID}"
    trapAdd "storpoolVolumeDelete \"${SP_VOL}\" \"force\""

    storpoolVolumeAttach "${SP_VOL}" "${HVHOST}"

    "${SSH:-ssh}" "${HVHOST}" "ln -sf \"/dev/storpool/${SP_VOL}\" \"${FILE}\""
    splog "${SSH:-ssh} ${HVHOST} ln -sf '/dev/storpool/${SP_VOL}' '${FILE}' ($?)"

    oneVmInfo "${VM_ID}"

    storpoolVolumeTag "${SP_VOL}" "virt;${LOC_TAG:-nloc};${VM_TAG:-nvm};${VC_POLICY:+vc-policy};type" "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};CHKPNT"

    trapReset
fi

splog "END ${VM_ID}"
exit 0
