#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

DRIVER_PATH=$(dirname "$0")

DRV_ACTION="$(cat)"
# shellcheck source=/dev/null
source "${DRIVER_PATH}/../../scripts_common.sh"
# shellcheck source=tm/storpool/storpool_common.sh
source "${DRIVER_PATH}/storpool_common.sh"

DEPLOY_ID="$1"
FILE="$2"
HVHOST="$3"
VM_ID="$4"
HVHOST2="$5"

splog "${DEPLOY_ID} ${FILE} ${HVHOST} ${VM_ID} ${HVHOST2} ${DRV_ACTION:0:8}"

if boolTrue "SP_CHECKPOINT_BD"; then
    read -r -a DS_ID_A <<< "${FILE//\// }"
    DS_ID="${DS_ID_A[-3]}"
    oneDatastoreInfo "${DS_ID}"

    SP_VOL="${ONE_PX}-sys-${VM_ID}-rawcheckpoint"

    if kvGetUid "${SP_VOL}"; then
        storpoolDelete "${SP_UID}" "force" "" "" "\"sys\":\"${SP_VOL}\""
    fi
    XPATH="${DRIVER_PATH}/../../datastore/xpath.rb"
    VM_MEMORY=$(echo "${DRV_ACTION}" | base64 -d | \
                      "${XPATH}" --stdin /VMM_DRIVER_ACTION_DATA/VM/TEMPLATE/MEMORY)

    oneVmInfo "${VM_ID}"

    storpoolVolumeCreate "${SP_VOL}" "$((VM_MEMORY*1024*1024*2))" "${ONE_PX}-ds-${DS_ID}" \
            "virt;${LOC_TAG:-nloc};${VM_TAG:-nvm};${VC_POLICY:+vc-policy};type" \
            "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};CHKPNT"
    kvGetUid "${SP_VOL}" fatal
    trapAdd APPEND "storpoolDelete \"${SP_UID}\" \"force\""

    oneHostInfo "${HVHOST}"
    DO_REMOTE="~${HOST_SP_CLUSTER_ID}" storpoolAttach "${SP_UID}" "${HVHOST}"

    SP_LINK="/dev/storpool-byid/${SP_UID#*~}"
    ${SSH:-ssh} "${HVHOST}" "ln -sf \"${SP_LINK}\" \"${FILE}\""
    splog "${SSH:-ssh} ${HVHOST} ln -sf \"${SP_LINK}\" \"${FILE}\" ($?)"

    trapReset
fi

splog "END ${VM_ID}"
exit 0
