#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2015-2025, StorPool (storpool.com)                               #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#-------------------------------------------------------------------------------
# snap_revert  host:parent_image snap_id vm_id ds_id
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Get snap_revert arguments from OpenNebula core
#-------------------------------------------------------------------------------

SRC="$1"
SNAP_ID="$2"
VM_ID="$3"
DS_ID="$4"

TM_PATH="$(dirname "$0")"
#shellcheck source=tm/storpool/storpool_common.sh
source "${TM_PATH}/storpool_common.sh"

splog "SRC=${SRC} SNAP_ID=${SNAP_ID} VM_ID=${VM_ID} DS_ID=${DS_ID}"

SRC_HOST="$(arg_host "${SRC}")"
SRC_PATH="$(arg_path "${SRC}")"
DISK_ID=$(echo "${SRC##*/}" | awk -F. '{print $NF}')

#-------------------------------------------------------------------------------
# Get Datastore information
#-------------------------------------------------------------------------------

oneDatastoreInfo "${DS_ID}"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

oneVmInfo "${VM_ID}" "${DISK_ID}"

#-------------------------------------------------------------------------------
# Compute the source image
#-------------------------------------------------------------------------------

xTYPE="PERS"

SP_VOL=${SOURCE##*/}
if boolTrue "CLONE"; then
    SP_VOL+="-${VM_ID}-${DISK_ID}"
    xTYPE="NPERS"
fi
if boolTrue "READONLY"; then
    xTYPE="${xTYPE}RO"
    if boolTrue "CDROM"; then
        xTYPE="CDROM"
    fi
fi

SP_SNAP="${SP_VOL}-snap${SNAP_ID}"
DST_HOST="${SRC_HOST}"

#-------------------------------------------------------------------------------
# Revert snapshot
#-------------------------------------------------------------------------------

kvGetUid "${SP_SNAP}" fatal
SNAP_UID="${SP_UID}"

kvGetUid "${SP_VOL}" fatal

storpoolVolumeInfo "${SP_UID}" byName

storpoolDetach "${SP_UID}" "force" "${SRC_HOST}" "all"

boolTrue "UPDATE_ONE_DISK_SIZE" && REVERT_SIZE=1 || REVERT_SIZE=0

storpoolVolumeRevert "${SP_UID}" "${SP_VOL}" "${SNAP_UID}" "${REMOTE_BACKUP_DELETE}" "${REVERT_SIZE}"
_RET=$?

if [[ ${_RET} -ne 0 ]]; then
    storpoolAttach "${SP_UID}" "${SRC_HOST}"
    oneSymlink "${SRC_HOST}" "${SP_UID}" "${SRC_PATH}"
    exit "${_RET}"
fi

if boolTrue "REVERT_SIZE"; then
    OLD_SIZE_M=$((V_SIZE/1024/1024))
    storpoolVolumeInfo "${SP_UID}" byName
    NEW_SIZE_M=$((V_SIZE/1024/1024))
    if [[ ${OLD_SIZE_M} -ne ${NEW_SIZE_M} ]]; then
        oneVmVolumes "${VM_ID}"
        declare -A vmVolumesMap_a
        for disk in ${vmDisksMap}; do
            vmVolumesMap_a["${disk%:*}"]="${disk##*:}"
        done
        if [[ -n "${vmVolumesMap_a["${SP_VOL}"]}" ]]; then
            DISK_ID="${vmVolumesMap_a["${SP_VOL}"]}"
            onedb change-body vm --id "${VM_ID}" "/VM/TEMPLATE/DISK[DISK_ID=${DISK_ID}]/SIZE" "${NEW_SIZE_M}"
            splog "[I] onedb change VM_ID:${VM_ID} DISK_ID:${DISK_ID} SIZE:${NEW_SIZE_M} (OLD_SIZE:${OLD_SIZE_M})($?)"
        else
            splog "[W] vmVolumesMap_a[${SP_VOL}] not found"
        fi
    fi
fi

storpoolAttach "${SP_UID}" "${SRC_HOST}"

storpoolVolumeTag "${SP_UID}" \
        "virt;${LOC_TAG:-nloc};${VM_TAG:-nvm};${VC_POLICY:+vc-policy};${SP_QOSCLASS:+qc};type;diskid" \
        "one;${LOC_TAG_VAL};${VM_ID};${VC_POLICY};${SP_QOSCLASS};${xTYPE};${DISK_ID}"

oneSymlink "${SRC_HOST}" "${SP_UID}" "${SRC_PATH}"

splog "END ${VM_ID}"
exit 0
